services:
  db:
    image: postgres:11-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gym
    ports:
      - 15432:5432
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000 
    environment:
      - DB_HOST=db
      - DB_PORT=5432
    entrypoint: "npm run start"