// This file is auto-generated by @hey-api/openapi-ts

import {
  type Options,
  postAuthRegister,
  postAuthLogin,
  getExercises,
  postExercises,
  putExercises,
  getExercisesBuiltIn,
  deleteExercisesById,
  getExercisesById,
  patchExercisesById,
  getWorkouts,
  postWorkouts,
  putWorkouts,
  deleteWorkoutsById,
  getWorkoutsById,
  patchWorkoutsById,
  postWeight,
  getArgusCheckin,
  getArgusCheckinTypes,
} from "../sdk.gen";
import {
  queryOptions,
  type UseMutationOptions,
  infiniteQueryOptions,
  type InfiniteData,
} from "@tanstack/react-query";
import type {
  PostAuthRegisterData,
  PostAuthRegisterError,
  PostAuthRegisterResponse,
  PostAuthLoginData,
  PostAuthLoginError,
  PostAuthLoginResponse,
  GetExercisesData,
  PostExercisesData,
  PostExercisesError,
  PostExercisesResponse,
  PutExercisesData,
  PutExercisesError,
  PutExercisesResponse,
  GetExercisesBuiltInData,
  DeleteExercisesByIdData,
  DeleteExercisesByIdError,
  DeleteExercisesByIdResponse,
  GetExercisesByIdData,
  PatchExercisesByIdData,
  PatchExercisesByIdError,
  PatchExercisesByIdResponse,
  GetWorkoutsData,
  GetWorkoutsError,
  GetWorkoutsResponse,
  PostWorkoutsData,
  PostWorkoutsError,
  PostWorkoutsResponse,
  PutWorkoutsData,
  PutWorkoutsError,
  PutWorkoutsResponse,
  DeleteWorkoutsByIdData,
  DeleteWorkoutsByIdError,
  DeleteWorkoutsByIdResponse,
  GetWorkoutsByIdData,
  PatchWorkoutsByIdData,
  PatchWorkoutsByIdError,
  PatchWorkoutsByIdResponse,
  PostWeightData,
  PostWeightError,
  PostWeightResponse,
  GetArgusCheckinData,
  GetArgusCheckinError,
  GetArgusCheckinResponse,
  GetArgusCheckinTypesData,
} from "../types.gen";
import type { AxiosError } from "axios";
import { client as _heyApiClient } from "../client.gen";

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseURL" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseURL: (options?.client ?? _heyApiClient).getConfig().baseURL,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const postAuthRegisterQueryKey = (
  options?: Options<PostAuthRegisterData>,
) => createQueryKey("postAuthRegister", options);

/**
 * Registers a user
 */
export const postAuthRegisterOptions = (
  options?: Options<PostAuthRegisterData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postAuthRegister({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postAuthRegisterQueryKey(options),
  });
};

/**
 * Registers a user
 */
export const postAuthRegisterMutation = (
  options?: Partial<Options<PostAuthRegisterData>>,
): UseMutationOptions<
  PostAuthRegisterResponse,
  AxiosError<PostAuthRegisterError>,
  Options<PostAuthRegisterData>
> => {
  const mutationOptions: UseMutationOptions<
    PostAuthRegisterResponse,
    AxiosError<PostAuthRegisterError>,
    Options<PostAuthRegisterData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postAuthRegister({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const postAuthLoginQueryKey = (options?: Options<PostAuthLoginData>) =>
  createQueryKey("postAuthLogin", options);

/**
 * Logins a user
 */
export const postAuthLoginOptions = (options?: Options<PostAuthLoginData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postAuthLogin({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postAuthLoginQueryKey(options),
  });
};

/**
 * Logins a user
 */
export const postAuthLoginMutation = (
  options?: Partial<Options<PostAuthLoginData>>,
): UseMutationOptions<
  PostAuthLoginResponse,
  AxiosError<PostAuthLoginError>,
  Options<PostAuthLoginData>
> => {
  const mutationOptions: UseMutationOptions<
    PostAuthLoginResponse,
    AxiosError<PostAuthLoginError>,
    Options<PostAuthLoginData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postAuthLogin({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getExercisesQueryKey = (options?: Options<GetExercisesData>) =>
  createQueryKey("getExercises", options);

/**
 * Returns data on exercises available to the user
 */
export const getExercisesOptions = (options?: Options<GetExercisesData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getExercises({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getExercisesQueryKey(options),
  });
};

export const postExercisesQueryKey = (options?: Options<PostExercisesData>) =>
  createQueryKey("postExercises", options);

/**
 * Adds new exercise to the user personal library
 */
export const postExercisesOptions = (options?: Options<PostExercisesData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postExercises({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postExercisesQueryKey(options),
  });
};

/**
 * Adds new exercise to the user personal library
 */
export const postExercisesMutation = (
  options?: Partial<Options<PostExercisesData>>,
): UseMutationOptions<
  PostExercisesResponse,
  AxiosError<PostExercisesError>,
  Options<PostExercisesData>
> => {
  const mutationOptions: UseMutationOptions<
    PostExercisesResponse,
    AxiosError<PostExercisesError>,
    Options<PostExercisesData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postExercises({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Updates or inserts exercise in users personal library
 */
export const putExercisesMutation = (
  options?: Partial<Options<PutExercisesData>>,
): UseMutationOptions<
  PutExercisesResponse,
  AxiosError<PutExercisesError>,
  Options<PutExercisesData>
> => {
  const mutationOptions: UseMutationOptions<
    PutExercisesResponse,
    AxiosError<PutExercisesError>,
    Options<PutExercisesData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await putExercises({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getExercisesBuiltInQueryKey = (
  options?: Options<GetExercisesBuiltInData>,
) => createQueryKey("getExercisesBuiltIn", options);

/**
 * Returns data on exercises available to the user
 */
export const getExercisesBuiltInOptions = (
  options?: Options<GetExercisesBuiltInData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getExercisesBuiltIn({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getExercisesBuiltInQueryKey(options),
  });
};

/**
 * Deletes exercise from users personal library
 */
export const deleteExercisesByIdMutation = (
  options?: Partial<Options<DeleteExercisesByIdData>>,
): UseMutationOptions<
  DeleteExercisesByIdResponse,
  AxiosError<DeleteExercisesByIdError>,
  Options<DeleteExercisesByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteExercisesByIdResponse,
    AxiosError<DeleteExercisesByIdError>,
    Options<DeleteExercisesByIdData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await deleteExercisesById({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getExercisesByIdQueryKey = (
  options: Options<GetExercisesByIdData>,
) => createQueryKey("getExercisesById", options);

/**
 * Returns data on an exercise available to the user
 */
export const getExercisesByIdOptions = (
  options: Options<GetExercisesByIdData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getExercisesById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getExercisesByIdQueryKey(options),
  });
};

/**
 * Updates exercise in users personal library
 */
export const patchExercisesByIdMutation = (
  options?: Partial<Options<PatchExercisesByIdData>>,
): UseMutationOptions<
  PatchExercisesByIdResponse,
  AxiosError<PatchExercisesByIdError>,
  Options<PatchExercisesByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    PatchExercisesByIdResponse,
    AxiosError<PatchExercisesByIdError>,
    Options<PatchExercisesByIdData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await patchExercisesById({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getWorkoutsQueryKey = (options?: Options<GetWorkoutsData>) =>
  createQueryKey("getWorkouts", options);

/**
 * Returns list of users workouts
 */
export const getWorkoutsOptions = (options?: Options<GetWorkoutsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getWorkouts({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getWorkoutsQueryKey(options),
  });
};

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], "body" | "headers" | "path" | "query">,
>(
  queryKey: QueryKey<Options>,
  page: K,
) => {
  const params = {
    ...queryKey[0],
  };
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    };
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    };
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    };
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    };
  }
  return params as unknown as typeof page;
};

export const getWorkoutsInfiniteQueryKey = (
  options?: Options<GetWorkoutsData>,
): QueryKey<Options<GetWorkoutsData>> =>
  createQueryKey("getWorkouts", options, true);

/**
 * Returns list of users workouts
 */
export const getWorkoutsInfiniteOptions = (
  options?: Options<GetWorkoutsData>,
) => {
  return infiniteQueryOptions<
    GetWorkoutsResponse,
    AxiosError<GetWorkoutsError>,
    InfiniteData<GetWorkoutsResponse>,
    QueryKey<Options<GetWorkoutsData>>,
    | number
    | Pick<
        QueryKey<Options<GetWorkoutsData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetWorkoutsData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getWorkouts({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getWorkoutsInfiniteQueryKey(options),
    },
  );
};

export const postWorkoutsQueryKey = (options?: Options<PostWorkoutsData>) =>
  createQueryKey("postWorkouts", options);

/**
 * Adds new workout for the user
 */
export const postWorkoutsOptions = (options?: Options<PostWorkoutsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postWorkouts({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postWorkoutsQueryKey(options),
  });
};

/**
 * Adds new workout for the user
 */
export const postWorkoutsMutation = (
  options?: Partial<Options<PostWorkoutsData>>,
): UseMutationOptions<
  PostWorkoutsResponse,
  AxiosError<PostWorkoutsError>,
  Options<PostWorkoutsData>
> => {
  const mutationOptions: UseMutationOptions<
    PostWorkoutsResponse,
    AxiosError<PostWorkoutsError>,
    Options<PostWorkoutsData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postWorkouts({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Updates or inserts workout for user
 */
export const putWorkoutsMutation = (
  options?: Partial<Options<PutWorkoutsData>>,
): UseMutationOptions<
  PutWorkoutsResponse,
  AxiosError<PutWorkoutsError>,
  Options<PutWorkoutsData>
> => {
  const mutationOptions: UseMutationOptions<
    PutWorkoutsResponse,
    AxiosError<PutWorkoutsError>,
    Options<PutWorkoutsData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await putWorkouts({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Deletes workout from user
 */
export const deleteWorkoutsByIdMutation = (
  options?: Partial<Options<DeleteWorkoutsByIdData>>,
): UseMutationOptions<
  DeleteWorkoutsByIdResponse,
  AxiosError<DeleteWorkoutsByIdError>,
  Options<DeleteWorkoutsByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteWorkoutsByIdResponse,
    AxiosError<DeleteWorkoutsByIdError>,
    Options<DeleteWorkoutsByIdData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await deleteWorkoutsById({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getWorkoutsByIdQueryKey = (
  options: Options<GetWorkoutsByIdData>,
) => createQueryKey("getWorkoutsById", options);

/**
 * Returns data on user workout
 */
export const getWorkoutsByIdOptions = (
  options: Options<GetWorkoutsByIdData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getWorkoutsById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getWorkoutsByIdQueryKey(options),
  });
};

/**
 * Updates workout of current user
 */
export const patchWorkoutsByIdMutation = (
  options?: Partial<Options<PatchWorkoutsByIdData>>,
): UseMutationOptions<
  PatchWorkoutsByIdResponse,
  AxiosError<PatchWorkoutsByIdError>,
  Options<PatchWorkoutsByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    PatchWorkoutsByIdResponse,
    AxiosError<PatchWorkoutsByIdError>,
    Options<PatchWorkoutsByIdData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await patchWorkoutsById({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const postWeightQueryKey = (options?: Options<PostWeightData>) =>
  createQueryKey("postWeight", options);

/**
 * Adds new weight entry for the user
 */
export const postWeightOptions = (options?: Options<PostWeightData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postWeight({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postWeightQueryKey(options),
  });
};

/**
 * Adds new weight entry for the user
 */
export const postWeightMutation = (
  options?: Partial<Options<PostWeightData>>,
): UseMutationOptions<
  PostWeightResponse,
  AxiosError<PostWeightError>,
  Options<PostWeightData>
> => {
  const mutationOptions: UseMutationOptions<
    PostWeightResponse,
    AxiosError<PostWeightError>,
    Options<PostWeightData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postWeight({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getArgusCheckinQueryKey = (
  options?: Options<GetArgusCheckinData>,
) => createQueryKey("getArgusCheckin", options);

/**
 * Returns data on all checkins from Argus
 */
export const getArgusCheckinOptions = (
  options?: Options<GetArgusCheckinData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getArgusCheckin({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getArgusCheckinQueryKey(options),
  });
};

export const getArgusCheckinInfiniteQueryKey = (
  options?: Options<GetArgusCheckinData>,
): QueryKey<Options<GetArgusCheckinData>> =>
  createQueryKey("getArgusCheckin", options, true);

/**
 * Returns data on all checkins from Argus
 */
export const getArgusCheckinInfiniteOptions = (
  options?: Options<GetArgusCheckinData>,
) => {
  return infiniteQueryOptions<
    GetArgusCheckinResponse,
    AxiosError<GetArgusCheckinError>,
    InfiniteData<GetArgusCheckinResponse>,
    QueryKey<Options<GetArgusCheckinData>>,
    | number
    | Pick<
        QueryKey<Options<GetArgusCheckinData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetArgusCheckinData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getArgusCheckin({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getArgusCheckinInfiniteQueryKey(options),
    },
  );
};

export const getArgusCheckinTypesQueryKey = (
  options?: Options<GetArgusCheckinTypesData>,
) => createQueryKey("getArgusCheckinTypes", options);

/**
 * Returns possible checkin types for Argus
 */
export const getArgusCheckinTypesOptions = (
  options?: Options<GetArgusCheckinTypesData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getArgusCheckinTypes({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getArgusCheckinTypesQueryKey(options),
  });
};
