ALTER TABLE "gym_tracker"."argus-checkins" ALTER COLUMN "id" SET GENERATED BY DEFAULT;--> statement-breakpoint
ALTER TABLE "gym_tracker"."exercise_muscles" ALTER COLUMN "id" SET GENERATED BY DEFAULT;--> statement-breakpoint
ALTER TABLE "gym_tracker"."users" ALTER COLUMN "id" SET GENERATED BY DEFAULT;