// This file is auto-generated by @hey-api/openapi-ts

import {
  type Options,
  register,
  login,
  startPasswordReset,
  finishPasswordReset,
  changePassword,
  getExercises,
  postExercises,
  putExercises,
  getExercisesBuiltIn,
  deleteExercisesById,
  getExercisesById,
  patchExercisesById,
  getWorkouts,
  postWorkouts,
  putWorkouts,
  deleteWorkoutsById,
  getWorkoutsById,
  patchWorkoutsById,
  getWorkoutPlans,
  postWorkoutPlans,
  deleteWorkoutPlansById,
  getWorkoutPlansById,
  patchWorkoutPlansById,
  getWorkoutTypes,
  postWorkoutTypes,
  deleteWorkoutTypesById,
  getWorkoutTypesById,
  patchWorkoutTypesById,
  postWeight,
  getWeightById,
  patchWeightById,
  getArgusCheckin,
  getArgusCheckinTypes,
  getEntriesOwn,
  deleteEntriesById,
  getEntriesById,
  getEntries,
  putEntries,
  getEntriesOwnDates,
  postPosts,
  getPostsById,
  patchPostsById,
  getFoodList,
  upsertFood,
  upsertFoods,
  findFood,
  getFood,
  scanBarcode,
  getOwnProfile,
  getSettings,
  updateSettings,
  getCrmUsers,
  getCrmManagers,
  managerLogin,
  getCrmTranslationsById,
  patchCrmTranslationsById,
  getCrmTranslations,
  getCrmExercisesById,
  patchCrmExercisesById,
  getCrmExercises,
  getCrmImages,
  deleteCrmImagesById,
} from "../sdk.gen";
import {
  queryOptions,
  type UseMutationOptions,
  infiniteQueryOptions,
  type InfiniteData,
} from "@tanstack/react-query";
import type {
  RegisterData,
  RegisterError,
  RegisterResponse,
  LoginData,
  LoginError,
  LoginResponse,
  StartPasswordResetData,
  StartPasswordResetError,
  StartPasswordResetResponse,
  FinishPasswordResetData,
  FinishPasswordResetError,
  FinishPasswordResetResponse,
  ChangePasswordData,
  ChangePasswordError,
  ChangePasswordResponse,
  GetExercisesData,
  GetExercisesError,
  GetExercisesResponse,
  PostExercisesData,
  PostExercisesError,
  PostExercisesResponse,
  PutExercisesData,
  PutExercisesError,
  PutExercisesResponse,
  GetExercisesBuiltInData,
  GetExercisesBuiltInError,
  GetExercisesBuiltInResponse,
  DeleteExercisesByIdData,
  DeleteExercisesByIdError,
  DeleteExercisesByIdResponse,
  GetExercisesByIdData,
  PatchExercisesByIdData,
  PatchExercisesByIdError,
  PatchExercisesByIdResponse,
  GetWorkoutsData,
  GetWorkoutsError,
  GetWorkoutsResponse,
  PostWorkoutsData,
  PostWorkoutsError,
  PostWorkoutsResponse,
  PutWorkoutsData,
  PutWorkoutsError,
  PutWorkoutsResponse,
  DeleteWorkoutsByIdData,
  DeleteWorkoutsByIdError,
  DeleteWorkoutsByIdResponse,
  GetWorkoutsByIdData,
  PatchWorkoutsByIdData,
  PatchWorkoutsByIdError,
  PatchWorkoutsByIdResponse,
  GetWorkoutPlansData,
  GetWorkoutPlansError,
  GetWorkoutPlansResponse,
  PostWorkoutPlansData,
  PostWorkoutPlansError,
  PostWorkoutPlansResponse,
  DeleteWorkoutPlansByIdData,
  DeleteWorkoutPlansByIdError,
  DeleteWorkoutPlansByIdResponse,
  GetWorkoutPlansByIdData,
  PatchWorkoutPlansByIdData,
  PatchWorkoutPlansByIdError,
  PatchWorkoutPlansByIdResponse,
  GetWorkoutTypesData,
  GetWorkoutTypesError,
  GetWorkoutTypesResponse,
  PostWorkoutTypesData,
  PostWorkoutTypesError,
  PostWorkoutTypesResponse,
  DeleteWorkoutTypesByIdData,
  DeleteWorkoutTypesByIdError,
  DeleteWorkoutTypesByIdResponse,
  GetWorkoutTypesByIdData,
  PatchWorkoutTypesByIdData,
  PatchWorkoutTypesByIdError,
  PatchWorkoutTypesByIdResponse,
  PostWeightData,
  PostWeightError,
  PostWeightResponse,
  GetWeightByIdData,
  PatchWeightByIdData,
  PatchWeightByIdError,
  PatchWeightByIdResponse,
  GetArgusCheckinData,
  GetArgusCheckinError,
  GetArgusCheckinResponse,
  GetArgusCheckinTypesData,
  GetEntriesOwnData,
  GetEntriesOwnError,
  GetEntriesOwnResponse,
  DeleteEntriesByIdData,
  DeleteEntriesByIdError,
  DeleteEntriesByIdResponse,
  GetEntriesByIdData,
  GetEntriesData,
  GetEntriesError,
  GetEntriesResponse,
  PutEntriesData,
  PutEntriesError,
  PutEntriesResponse,
  GetEntriesOwnDatesData,
  PostPostsData,
  PostPostsError,
  PostPostsResponse,
  GetPostsByIdData,
  PatchPostsByIdData,
  PatchPostsByIdError,
  PatchPostsByIdResponse,
  GetFoodListData,
  GetFoodListError,
  GetFoodListResponse,
  UpsertFoodData,
  UpsertFoodError,
  UpsertFoodResponse,
  UpsertFoodsData,
  UpsertFoodsError,
  UpsertFoodsResponse,
  FindFoodData,
  FindFoodError,
  FindFoodResponse,
  GetFoodData,
  GetFoodError,
  GetFoodResponse,
  ScanBarcodeData,
  ScanBarcodeError,
  ScanBarcodeResponse,
  GetOwnProfileData,
  GetSettingsData,
  UpdateSettingsData,
  UpdateSettingsError,
  UpdateSettingsResponse,
  GetCrmUsersData,
  GetCrmUsersError,
  GetCrmUsersResponse,
  GetCrmManagersData,
  GetCrmManagersError,
  GetCrmManagersResponse,
  ManagerLoginData,
  ManagerLoginError,
  ManagerLoginResponse,
  GetCrmTranslationsByIdData,
  PatchCrmTranslationsByIdData,
  PatchCrmTranslationsByIdError,
  PatchCrmTranslationsByIdResponse,
  GetCrmTranslationsData,
  GetCrmTranslationsError,
  GetCrmTranslationsResponse,
  GetCrmExercisesByIdData,
  PatchCrmExercisesByIdData,
  PatchCrmExercisesByIdError,
  PatchCrmExercisesByIdResponse,
  GetCrmExercisesData,
  GetCrmExercisesError,
  GetCrmExercisesResponse,
  GetCrmImagesData,
  GetCrmImagesError,
  GetCrmImagesResponse,
  DeleteCrmImagesByIdData,
  DeleteCrmImagesByIdError,
  DeleteCrmImagesByIdResponse,
} from "../types.gen";
import type { AxiosError } from "axios";
import { client as _heyApiClient } from "../client.gen";

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseURL" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseURL: (options?.client ?? _heyApiClient).getConfig().baseURL,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const registerQueryKey = (options?: Options<RegisterData>) =>
  createQueryKey("register", options);

/**
 * Registers a user
 */
export const registerOptions = (options?: Options<RegisterData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await register({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: registerQueryKey(options),
  });
};

/**
 * Registers a user
 */
export const registerMutation = (
  options?: Partial<Options<RegisterData>>,
): UseMutationOptions<
  RegisterResponse,
  AxiosError<RegisterError>,
  Options<RegisterData>
> => {
  const mutationOptions: UseMutationOptions<
    RegisterResponse,
    AxiosError<RegisterError>,
    Options<RegisterData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await register({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const loginQueryKey = (options?: Options<LoginData>) =>
  createQueryKey("login", options);

/**
 * Logins a user
 */
export const loginOptions = (options?: Options<LoginData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await login({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: loginQueryKey(options),
  });
};

/**
 * Logins a user
 */
export const loginMutation = (
  options?: Partial<Options<LoginData>>,
): UseMutationOptions<
  LoginResponse,
  AxiosError<LoginError>,
  Options<LoginData>
> => {
  const mutationOptions: UseMutationOptions<
    LoginResponse,
    AxiosError<LoginError>,
    Options<LoginData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await login({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const startPasswordResetQueryKey = (
  options?: Options<StartPasswordResetData>,
) => createQueryKey("startPasswordReset", options);

/**
 * Sends a password reset email for a user
 */
export const startPasswordResetOptions = (
  options?: Options<StartPasswordResetData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await startPasswordReset({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: startPasswordResetQueryKey(options),
  });
};

/**
 * Sends a password reset email for a user
 */
export const startPasswordResetMutation = (
  options?: Partial<Options<StartPasswordResetData>>,
): UseMutationOptions<
  StartPasswordResetResponse,
  AxiosError<StartPasswordResetError>,
  Options<StartPasswordResetData>
> => {
  const mutationOptions: UseMutationOptions<
    StartPasswordResetResponse,
    AxiosError<StartPasswordResetError>,
    Options<StartPasswordResetData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await startPasswordReset({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const finishPasswordResetQueryKey = (
  options?: Options<FinishPasswordResetData>,
) => createQueryKey("finishPasswordReset", options);

/**
 * Resets the user password and logs the user in
 */
export const finishPasswordResetOptions = (
  options?: Options<FinishPasswordResetData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await finishPasswordReset({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: finishPasswordResetQueryKey(options),
  });
};

/**
 * Resets the user password and logs the user in
 */
export const finishPasswordResetMutation = (
  options?: Partial<Options<FinishPasswordResetData>>,
): UseMutationOptions<
  FinishPasswordResetResponse,
  AxiosError<FinishPasswordResetError>,
  Options<FinishPasswordResetData>
> => {
  const mutationOptions: UseMutationOptions<
    FinishPasswordResetResponse,
    AxiosError<FinishPasswordResetError>,
    Options<FinishPasswordResetData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await finishPasswordReset({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const changePasswordQueryKey = (options?: Options<ChangePasswordData>) =>
  createQueryKey("changePassword", options);

/**
 * Changes the password of the user
 */
export const changePasswordOptions = (
  options?: Options<ChangePasswordData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await changePassword({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: changePasswordQueryKey(options),
  });
};

/**
 * Changes the password of the user
 */
export const changePasswordMutation = (
  options?: Partial<Options<ChangePasswordData>>,
): UseMutationOptions<
  ChangePasswordResponse,
  AxiosError<ChangePasswordError>,
  Options<ChangePasswordData>
> => {
  const mutationOptions: UseMutationOptions<
    ChangePasswordResponse,
    AxiosError<ChangePasswordError>,
    Options<ChangePasswordData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await changePassword({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getExercisesQueryKey = (options?: Options<GetExercisesData>) =>
  createQueryKey("getExercises", options);

/**
 * Returns data on exercises available to the user
 */
export const getExercisesOptions = (options?: Options<GetExercisesData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getExercises({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getExercisesQueryKey(options),
  });
};

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], "body" | "headers" | "path" | "query">,
>(
  queryKey: QueryKey<Options>,
  page: K,
) => {
  const params = {
    ...queryKey[0],
  };
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    };
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    };
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    };
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    };
  }
  return params as unknown as typeof page;
};

export const getExercisesInfiniteQueryKey = (
  options?: Options<GetExercisesData>,
): QueryKey<Options<GetExercisesData>> =>
  createQueryKey("getExercises", options, true);

/**
 * Returns data on exercises available to the user
 */
export const getExercisesInfiniteOptions = (
  options?: Options<GetExercisesData>,
) => {
  return infiniteQueryOptions<
    GetExercisesResponse,
    AxiosError<GetExercisesError>,
    InfiniteData<GetExercisesResponse>,
    QueryKey<Options<GetExercisesData>>,
    | number
    | Pick<
        QueryKey<Options<GetExercisesData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetExercisesData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getExercises({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getExercisesInfiniteQueryKey(options),
    },
  );
};

export const postExercisesQueryKey = (options?: Options<PostExercisesData>) =>
  createQueryKey("postExercises", options);

/**
 * Adds new exercise to the user personal library
 */
export const postExercisesOptions = (options?: Options<PostExercisesData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postExercises({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postExercisesQueryKey(options),
  });
};

/**
 * Adds new exercise to the user personal library
 */
export const postExercisesMutation = (
  options?: Partial<Options<PostExercisesData>>,
): UseMutationOptions<
  PostExercisesResponse,
  AxiosError<PostExercisesError>,
  Options<PostExercisesData>
> => {
  const mutationOptions: UseMutationOptions<
    PostExercisesResponse,
    AxiosError<PostExercisesError>,
    Options<PostExercisesData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postExercises({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Updates or inserts exercise in users personal library
 */
export const putExercisesMutation = (
  options?: Partial<Options<PutExercisesData>>,
): UseMutationOptions<
  PutExercisesResponse,
  AxiosError<PutExercisesError>,
  Options<PutExercisesData>
> => {
  const mutationOptions: UseMutationOptions<
    PutExercisesResponse,
    AxiosError<PutExercisesError>,
    Options<PutExercisesData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await putExercises({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getExercisesBuiltInQueryKey = (
  options?: Options<GetExercisesBuiltInData>,
) => createQueryKey("getExercisesBuiltIn", options);

/**
 * Returns data on exercises available to the user
 */
export const getExercisesBuiltInOptions = (
  options?: Options<GetExercisesBuiltInData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getExercisesBuiltIn({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getExercisesBuiltInQueryKey(options),
  });
};

export const getExercisesBuiltInInfiniteQueryKey = (
  options?: Options<GetExercisesBuiltInData>,
): QueryKey<Options<GetExercisesBuiltInData>> =>
  createQueryKey("getExercisesBuiltIn", options, true);

/**
 * Returns data on exercises available to the user
 */
export const getExercisesBuiltInInfiniteOptions = (
  options?: Options<GetExercisesBuiltInData>,
) => {
  return infiniteQueryOptions<
    GetExercisesBuiltInResponse,
    AxiosError<GetExercisesBuiltInError>,
    InfiniteData<GetExercisesBuiltInResponse>,
    QueryKey<Options<GetExercisesBuiltInData>>,
    | number
    | Pick<
        QueryKey<Options<GetExercisesBuiltInData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetExercisesBuiltInData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getExercisesBuiltIn({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getExercisesBuiltInInfiniteQueryKey(options),
    },
  );
};

/**
 * Deletes exercise from users personal library
 */
export const deleteExercisesByIdMutation = (
  options?: Partial<Options<DeleteExercisesByIdData>>,
): UseMutationOptions<
  DeleteExercisesByIdResponse,
  AxiosError<DeleteExercisesByIdError>,
  Options<DeleteExercisesByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteExercisesByIdResponse,
    AxiosError<DeleteExercisesByIdError>,
    Options<DeleteExercisesByIdData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await deleteExercisesById({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getExercisesByIdQueryKey = (
  options: Options<GetExercisesByIdData>,
) => createQueryKey("getExercisesById", options);

/**
 * Returns data on an library exercise available
 */
export const getExercisesByIdOptions = (
  options: Options<GetExercisesByIdData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getExercisesById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getExercisesByIdQueryKey(options),
  });
};

/**
 * Updates exercise in users personal library
 */
export const patchExercisesByIdMutation = (
  options?: Partial<Options<PatchExercisesByIdData>>,
): UseMutationOptions<
  PatchExercisesByIdResponse,
  AxiosError<PatchExercisesByIdError>,
  Options<PatchExercisesByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    PatchExercisesByIdResponse,
    AxiosError<PatchExercisesByIdError>,
    Options<PatchExercisesByIdData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await patchExercisesById({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getWorkoutsQueryKey = (options?: Options<GetWorkoutsData>) =>
  createQueryKey("getWorkouts", options);

/**
 * Returns list of user workouts
 */
export const getWorkoutsOptions = (options?: Options<GetWorkoutsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getWorkouts({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getWorkoutsQueryKey(options),
  });
};

export const getWorkoutsInfiniteQueryKey = (
  options?: Options<GetWorkoutsData>,
): QueryKey<Options<GetWorkoutsData>> =>
  createQueryKey("getWorkouts", options, true);

/**
 * Returns list of user workouts
 */
export const getWorkoutsInfiniteOptions = (
  options?: Options<GetWorkoutsData>,
) => {
  return infiniteQueryOptions<
    GetWorkoutsResponse,
    AxiosError<GetWorkoutsError>,
    InfiniteData<GetWorkoutsResponse>,
    QueryKey<Options<GetWorkoutsData>>,
    | number
    | Pick<
        QueryKey<Options<GetWorkoutsData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetWorkoutsData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getWorkouts({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getWorkoutsInfiniteQueryKey(options),
    },
  );
};

export const postWorkoutsQueryKey = (options?: Options<PostWorkoutsData>) =>
  createQueryKey("postWorkouts", options);

/**
 * Adds new workout for the user
 */
export const postWorkoutsOptions = (options?: Options<PostWorkoutsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postWorkouts({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postWorkoutsQueryKey(options),
  });
};

export const postWorkoutsInfiniteQueryKey = (
  options?: Options<PostWorkoutsData>,
): QueryKey<Options<PostWorkoutsData>> =>
  createQueryKey("postWorkouts", options, true);

/**
 * Adds new workout for the user
 */
export const postWorkoutsInfiniteOptions = (
  options?: Options<PostWorkoutsData>,
) => {
  return infiniteQueryOptions<
    PostWorkoutsResponse,
    AxiosError<PostWorkoutsError>,
    InfiniteData<PostWorkoutsResponse>,
    QueryKey<Options<PostWorkoutsData>>,
    | Date
    | Pick<
        QueryKey<Options<PostWorkoutsData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<PostWorkoutsData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                body: {
                  start: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await postWorkouts({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: postWorkoutsInfiniteQueryKey(options),
    },
  );
};

/**
 * Adds new workout for the user
 */
export const postWorkoutsMutation = (
  options?: Partial<Options<PostWorkoutsData>>,
): UseMutationOptions<
  PostWorkoutsResponse,
  AxiosError<PostWorkoutsError>,
  Options<PostWorkoutsData>
> => {
  const mutationOptions: UseMutationOptions<
    PostWorkoutsResponse,
    AxiosError<PostWorkoutsError>,
    Options<PostWorkoutsData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postWorkouts({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Updates or inserts workout for user
 */
export const putWorkoutsMutation = (
  options?: Partial<Options<PutWorkoutsData>>,
): UseMutationOptions<
  PutWorkoutsResponse,
  AxiosError<PutWorkoutsError>,
  Options<PutWorkoutsData>
> => {
  const mutationOptions: UseMutationOptions<
    PutWorkoutsResponse,
    AxiosError<PutWorkoutsError>,
    Options<PutWorkoutsData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await putWorkouts({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Deletes workout from user
 */
export const deleteWorkoutsByIdMutation = (
  options?: Partial<Options<DeleteWorkoutsByIdData>>,
): UseMutationOptions<
  DeleteWorkoutsByIdResponse,
  AxiosError<DeleteWorkoutsByIdError>,
  Options<DeleteWorkoutsByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteWorkoutsByIdResponse,
    AxiosError<DeleteWorkoutsByIdError>,
    Options<DeleteWorkoutsByIdData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await deleteWorkoutsById({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getWorkoutsByIdQueryKey = (
  options: Options<GetWorkoutsByIdData>,
) => createQueryKey("getWorkoutsById", options);

/**
 * Returns data on user workout
 */
export const getWorkoutsByIdOptions = (
  options: Options<GetWorkoutsByIdData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getWorkoutsById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getWorkoutsByIdQueryKey(options),
  });
};

/**
 * Updates workout of current user
 */
export const patchWorkoutsByIdMutation = (
  options?: Partial<Options<PatchWorkoutsByIdData>>,
): UseMutationOptions<
  PatchWorkoutsByIdResponse,
  AxiosError<PatchWorkoutsByIdError>,
  Options<PatchWorkoutsByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    PatchWorkoutsByIdResponse,
    AxiosError<PatchWorkoutsByIdError>,
    Options<PatchWorkoutsByIdData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await patchWorkoutsById({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getWorkoutPlansQueryKey = (
  options?: Options<GetWorkoutPlansData>,
) => createQueryKey("getWorkoutPlans", options);

/**
 * Returns list of user workout plans
 */
export const getWorkoutPlansOptions = (
  options?: Options<GetWorkoutPlansData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getWorkoutPlans({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getWorkoutPlansQueryKey(options),
  });
};

export const getWorkoutPlansInfiniteQueryKey = (
  options?: Options<GetWorkoutPlansData>,
): QueryKey<Options<GetWorkoutPlansData>> =>
  createQueryKey("getWorkoutPlans", options, true);

/**
 * Returns list of user workout plans
 */
export const getWorkoutPlansInfiniteOptions = (
  options?: Options<GetWorkoutPlansData>,
) => {
  return infiniteQueryOptions<
    GetWorkoutPlansResponse,
    AxiosError<GetWorkoutPlansError>,
    InfiniteData<GetWorkoutPlansResponse>,
    QueryKey<Options<GetWorkoutPlansData>>,
    | number
    | Pick<
        QueryKey<Options<GetWorkoutPlansData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetWorkoutPlansData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getWorkoutPlans({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getWorkoutPlansInfiniteQueryKey(options),
    },
  );
};

export const postWorkoutPlansQueryKey = (
  options?: Options<PostWorkoutPlansData>,
) => createQueryKey("postWorkoutPlans", options);

/**
 * Adds new workout plan for the user
 */
export const postWorkoutPlansOptions = (
  options?: Options<PostWorkoutPlansData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postWorkoutPlans({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postWorkoutPlansQueryKey(options),
  });
};

/**
 * Adds new workout plan for the user
 */
export const postWorkoutPlansMutation = (
  options?: Partial<Options<PostWorkoutPlansData>>,
): UseMutationOptions<
  PostWorkoutPlansResponse,
  AxiosError<PostWorkoutPlansError>,
  Options<PostWorkoutPlansData>
> => {
  const mutationOptions: UseMutationOptions<
    PostWorkoutPlansResponse,
    AxiosError<PostWorkoutPlansError>,
    Options<PostWorkoutPlansData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postWorkoutPlans({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Deletes workout plan
 */
export const deleteWorkoutPlansByIdMutation = (
  options?: Partial<Options<DeleteWorkoutPlansByIdData>>,
): UseMutationOptions<
  DeleteWorkoutPlansByIdResponse,
  AxiosError<DeleteWorkoutPlansByIdError>,
  Options<DeleteWorkoutPlansByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteWorkoutPlansByIdResponse,
    AxiosError<DeleteWorkoutPlansByIdError>,
    Options<DeleteWorkoutPlansByIdData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await deleteWorkoutPlansById({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getWorkoutPlansByIdQueryKey = (
  options: Options<GetWorkoutPlansByIdData>,
) => createQueryKey("getWorkoutPlansById", options);

/**
 * Returns data on user workout plan
 */
export const getWorkoutPlansByIdOptions = (
  options: Options<GetWorkoutPlansByIdData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getWorkoutPlansById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getWorkoutPlansByIdQueryKey(options),
  });
};

/**
 * Updated workout plan for the user
 */
export const patchWorkoutPlansByIdMutation = (
  options?: Partial<Options<PatchWorkoutPlansByIdData>>,
): UseMutationOptions<
  PatchWorkoutPlansByIdResponse,
  AxiosError<PatchWorkoutPlansByIdError>,
  Options<PatchWorkoutPlansByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    PatchWorkoutPlansByIdResponse,
    AxiosError<PatchWorkoutPlansByIdError>,
    Options<PatchWorkoutPlansByIdData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await patchWorkoutPlansById({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getWorkoutTypesQueryKey = (
  options?: Options<GetWorkoutTypesData>,
) => createQueryKey("getWorkoutTypes", options);

/**
 * Returns list of user workout plans
 */
export const getWorkoutTypesOptions = (
  options?: Options<GetWorkoutTypesData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getWorkoutTypes({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getWorkoutTypesQueryKey(options),
  });
};

export const getWorkoutTypesInfiniteQueryKey = (
  options?: Options<GetWorkoutTypesData>,
): QueryKey<Options<GetWorkoutTypesData>> =>
  createQueryKey("getWorkoutTypes", options, true);

/**
 * Returns list of user workout plans
 */
export const getWorkoutTypesInfiniteOptions = (
  options?: Options<GetWorkoutTypesData>,
) => {
  return infiniteQueryOptions<
    GetWorkoutTypesResponse,
    AxiosError<GetWorkoutTypesError>,
    InfiniteData<GetWorkoutTypesResponse>,
    QueryKey<Options<GetWorkoutTypesData>>,
    | number
    | Pick<
        QueryKey<Options<GetWorkoutTypesData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetWorkoutTypesData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getWorkoutTypes({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getWorkoutTypesInfiniteQueryKey(options),
    },
  );
};

export const postWorkoutTypesQueryKey = (
  options?: Options<PostWorkoutTypesData>,
) => createQueryKey("postWorkoutTypes", options);

/**
 * Adds new workout type for the user
 */
export const postWorkoutTypesOptions = (
  options?: Options<PostWorkoutTypesData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postWorkoutTypes({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postWorkoutTypesQueryKey(options),
  });
};

/**
 * Adds new workout type for the user
 */
export const postWorkoutTypesMutation = (
  options?: Partial<Options<PostWorkoutTypesData>>,
): UseMutationOptions<
  PostWorkoutTypesResponse,
  AxiosError<PostWorkoutTypesError>,
  Options<PostWorkoutTypesData>
> => {
  const mutationOptions: UseMutationOptions<
    PostWorkoutTypesResponse,
    AxiosError<PostWorkoutTypesError>,
    Options<PostWorkoutTypesData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postWorkoutTypes({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Deletes workout type
 */
export const deleteWorkoutTypesByIdMutation = (
  options?: Partial<Options<DeleteWorkoutTypesByIdData>>,
): UseMutationOptions<
  DeleteWorkoutTypesByIdResponse,
  AxiosError<DeleteWorkoutTypesByIdError>,
  Options<DeleteWorkoutTypesByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteWorkoutTypesByIdResponse,
    AxiosError<DeleteWorkoutTypesByIdError>,
    Options<DeleteWorkoutTypesByIdData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await deleteWorkoutTypesById({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getWorkoutTypesByIdQueryKey = (
  options: Options<GetWorkoutTypesByIdData>,
) => createQueryKey("getWorkoutTypesById", options);

/**
 * Returns data on user workout type
 */
export const getWorkoutTypesByIdOptions = (
  options: Options<GetWorkoutTypesByIdData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getWorkoutTypesById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getWorkoutTypesByIdQueryKey(options),
  });
};

/**
 * Updated workout type for the user
 */
export const patchWorkoutTypesByIdMutation = (
  options?: Partial<Options<PatchWorkoutTypesByIdData>>,
): UseMutationOptions<
  PatchWorkoutTypesByIdResponse,
  AxiosError<PatchWorkoutTypesByIdError>,
  Options<PatchWorkoutTypesByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    PatchWorkoutTypesByIdResponse,
    AxiosError<PatchWorkoutTypesByIdError>,
    Options<PatchWorkoutTypesByIdData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await patchWorkoutTypesById({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const postWeightQueryKey = (options?: Options<PostWeightData>) =>
  createQueryKey("postWeight", options);

/**
 * Adds new weight entry for the user
 */
export const postWeightOptions = (options?: Options<PostWeightData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postWeight({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postWeightQueryKey(options),
  });
};

/**
 * Adds new weight entry for the user
 */
export const postWeightMutation = (
  options?: Partial<Options<PostWeightData>>,
): UseMutationOptions<
  PostWeightResponse,
  AxiosError<PostWeightError>,
  Options<PostWeightData>
> => {
  const mutationOptions: UseMutationOptions<
    PostWeightResponse,
    AxiosError<PostWeightError>,
    Options<PostWeightData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postWeight({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getWeightByIdQueryKey = (options: Options<GetWeightByIdData>) =>
  createQueryKey("getWeightById", options);

/**
 * Gets own weight entry for the user
 */
export const getWeightByIdOptions = (options: Options<GetWeightByIdData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getWeightById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getWeightByIdQueryKey(options),
  });
};

/**
 * Updates own weight entry for the user
 */
export const patchWeightByIdMutation = (
  options?: Partial<Options<PatchWeightByIdData>>,
): UseMutationOptions<
  PatchWeightByIdResponse,
  AxiosError<PatchWeightByIdError>,
  Options<PatchWeightByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    PatchWeightByIdResponse,
    AxiosError<PatchWeightByIdError>,
    Options<PatchWeightByIdData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await patchWeightById({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getArgusCheckinQueryKey = (
  options?: Options<GetArgusCheckinData>,
) => createQueryKey("getArgusCheckin", options);

/**
 * Returns data on all checkins from Argus
 */
export const getArgusCheckinOptions = (
  options?: Options<GetArgusCheckinData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getArgusCheckin({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getArgusCheckinQueryKey(options),
  });
};

export const getArgusCheckinInfiniteQueryKey = (
  options?: Options<GetArgusCheckinData>,
): QueryKey<Options<GetArgusCheckinData>> =>
  createQueryKey("getArgusCheckin", options, true);

/**
 * Returns data on all checkins from Argus
 */
export const getArgusCheckinInfiniteOptions = (
  options?: Options<GetArgusCheckinData>,
) => {
  return infiniteQueryOptions<
    GetArgusCheckinResponse,
    AxiosError<GetArgusCheckinError>,
    InfiniteData<GetArgusCheckinResponse>,
    QueryKey<Options<GetArgusCheckinData>>,
    | number
    | Pick<
        QueryKey<Options<GetArgusCheckinData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetArgusCheckinData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getArgusCheckin({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getArgusCheckinInfiniteQueryKey(options),
    },
  );
};

export const getArgusCheckinTypesQueryKey = (
  options?: Options<GetArgusCheckinTypesData>,
) => createQueryKey("getArgusCheckinTypes", options);

/**
 * Returns possible checkin types for Argus
 */
export const getArgusCheckinTypesOptions = (
  options?: Options<GetArgusCheckinTypesData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getArgusCheckinTypes({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getArgusCheckinTypesQueryKey(options),
  });
};

export const getEntriesOwnQueryKey = (options?: Options<GetEntriesOwnData>) =>
  createQueryKey("getEntriesOwn", options);

/**
 * Returns the list of public entries
 */
export const getEntriesOwnOptions = (options?: Options<GetEntriesOwnData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getEntriesOwn({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getEntriesOwnQueryKey(options),
  });
};

export const getEntriesOwnInfiniteQueryKey = (
  options?: Options<GetEntriesOwnData>,
): QueryKey<Options<GetEntriesOwnData>> =>
  createQueryKey("getEntriesOwn", options, true);

/**
 * Returns the list of public entries
 */
export const getEntriesOwnInfiniteOptions = (
  options?: Options<GetEntriesOwnData>,
) => {
  return infiniteQueryOptions<
    GetEntriesOwnResponse,
    AxiosError<GetEntriesOwnError>,
    InfiniteData<GetEntriesOwnResponse>,
    QueryKey<Options<GetEntriesOwnData>>,
    | number
    | Pick<
        QueryKey<Options<GetEntriesOwnData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetEntriesOwnData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getEntriesOwn({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getEntriesOwnInfiniteQueryKey(options),
    },
  );
};

/**
 * Deletes entry for user
 */
export const deleteEntriesByIdMutation = (
  options?: Partial<Options<DeleteEntriesByIdData>>,
): UseMutationOptions<
  DeleteEntriesByIdResponse,
  AxiosError<DeleteEntriesByIdError>,
  Options<DeleteEntriesByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteEntriesByIdResponse,
    AxiosError<DeleteEntriesByIdError>,
    Options<DeleteEntriesByIdData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await deleteEntriesById({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getEntriesByIdQueryKey = (options: Options<GetEntriesByIdData>) =>
  createQueryKey("getEntriesById", options);

/**
 * Returns the list of public entries
 */
export const getEntriesByIdOptions = (options: Options<GetEntriesByIdData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getEntriesById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getEntriesByIdQueryKey(options),
  });
};

export const getEntriesQueryKey = (options?: Options<GetEntriesData>) =>
  createQueryKey("getEntries", options);

/**
 * Returns the list of public entries
 */
export const getEntriesOptions = (options?: Options<GetEntriesData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getEntries({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getEntriesQueryKey(options),
  });
};

export const getEntriesInfiniteQueryKey = (
  options?: Options<GetEntriesData>,
): QueryKey<Options<GetEntriesData>> =>
  createQueryKey("getEntries", options, true);

/**
 * Returns the list of public entries
 */
export const getEntriesInfiniteOptions = (
  options?: Options<GetEntriesData>,
) => {
  return infiniteQueryOptions<
    GetEntriesResponse,
    AxiosError<GetEntriesError>,
    InfiniteData<GetEntriesResponse>,
    QueryKey<Options<GetEntriesData>>,
    | number
    | Pick<
        QueryKey<Options<GetEntriesData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetEntriesData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getEntries({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getEntriesInfiniteQueryKey(options),
    },
  );
};

/**
 * Updates or inserts entries for user
 */
export const putEntriesMutation = (
  options?: Partial<Options<PutEntriesData>>,
): UseMutationOptions<
  PutEntriesResponse,
  AxiosError<PutEntriesError>,
  Options<PutEntriesData>
> => {
  const mutationOptions: UseMutationOptions<
    PutEntriesResponse,
    AxiosError<PutEntriesError>,
    Options<PutEntriesData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await putEntries({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getEntriesOwnDatesQueryKey = (
  options: Options<GetEntriesOwnDatesData>,
) => createQueryKey("getEntriesOwnDates", options);

/**
 * Returns the list of days when entries were logged
 */
export const getEntriesOwnDatesOptions = (
  options: Options<GetEntriesOwnDatesData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getEntriesOwnDates({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getEntriesOwnDatesQueryKey(options),
  });
};

export const postPostsQueryKey = (options?: Options<PostPostsData>) =>
  createQueryKey("postPosts", options);

/**
 * Adds new post entry for the user
 */
export const postPostsOptions = (options?: Options<PostPostsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postPosts({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postPostsQueryKey(options),
  });
};

/**
 * Adds new post entry for the user
 */
export const postPostsMutation = (
  options?: Partial<Options<PostPostsData>>,
): UseMutationOptions<
  PostPostsResponse,
  AxiosError<PostPostsError>,
  Options<PostPostsData>
> => {
  const mutationOptions: UseMutationOptions<
    PostPostsResponse,
    AxiosError<PostPostsError>,
    Options<PostPostsData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postPosts({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getPostsByIdQueryKey = (options: Options<GetPostsByIdData>) =>
  createQueryKey("getPostsById", options);

/**
 * Adds new post entry for the user
 */
export const getPostsByIdOptions = (options: Options<GetPostsByIdData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getPostsById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getPostsByIdQueryKey(options),
  });
};

/**
 * Updates post entry for the user
 */
export const patchPostsByIdMutation = (
  options?: Partial<Options<PatchPostsByIdData>>,
): UseMutationOptions<
  PatchPostsByIdResponse,
  AxiosError<PatchPostsByIdError>,
  Options<PatchPostsByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    PatchPostsByIdResponse,
    AxiosError<PatchPostsByIdError>,
    Options<PatchPostsByIdData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await patchPostsById({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getFoodListQueryKey = (options?: Options<GetFoodListData>) =>
  createQueryKey("getFoodList", options);

/**
 * Updates or inserts food for user
 */
export const getFoodListOptions = (options?: Options<GetFoodListData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getFoodList({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getFoodListQueryKey(options),
  });
};

export const getFoodListInfiniteQueryKey = (
  options?: Options<GetFoodListData>,
): QueryKey<Options<GetFoodListData>> =>
  createQueryKey("getFoodList", options, true);

/**
 * Updates or inserts food for user
 */
export const getFoodListInfiniteOptions = (
  options?: Options<GetFoodListData>,
) => {
  return infiniteQueryOptions<
    GetFoodListResponse,
    AxiosError<GetFoodListError>,
    InfiniteData<GetFoodListResponse>,
    QueryKey<Options<GetFoodListData>>,
    | number
    | Pick<
        QueryKey<Options<GetFoodListData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetFoodListData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getFoodList({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getFoodListInfiniteQueryKey(options),
    },
  );
};

/**
 * Updates or inserts food for user
 */
export const upsertFoodMutation = (
  options?: Partial<Options<UpsertFoodData>>,
): UseMutationOptions<
  UpsertFoodResponse,
  AxiosError<UpsertFoodError>,
  Options<UpsertFoodData>
> => {
  const mutationOptions: UseMutationOptions<
    UpsertFoodResponse,
    AxiosError<UpsertFoodError>,
    Options<UpsertFoodData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await upsertFood({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Updates or inserts food for user
 */
export const upsertFoodsMutation = (
  options?: Partial<Options<UpsertFoodsData>>,
): UseMutationOptions<
  UpsertFoodsResponse,
  AxiosError<UpsertFoodsError>,
  Options<UpsertFoodsData>
> => {
  const mutationOptions: UseMutationOptions<
    UpsertFoodsResponse,
    AxiosError<UpsertFoodsError>,
    Options<UpsertFoodsData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await upsertFoods({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const findFoodQueryKey = (options?: Options<FindFoodData>) =>
  createQueryKey("findFood", options);

/**
 * Search for food by name
 */
export const findFoodOptions = (options?: Options<FindFoodData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await findFood({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: findFoodQueryKey(options),
  });
};

export const findFoodInfiniteQueryKey = (
  options?: Options<FindFoodData>,
): QueryKey<Options<FindFoodData>> => createQueryKey("findFood", options, true);

/**
 * Search for food by name
 */
export const findFoodInfiniteOptions = (options?: Options<FindFoodData>) => {
  return infiniteQueryOptions<
    FindFoodResponse,
    AxiosError<FindFoodError>,
    InfiniteData<FindFoodResponse>,
    QueryKey<Options<FindFoodData>>,
    | string
    | Pick<
        QueryKey<Options<FindFoodData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<FindFoodData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  cursor: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await findFood({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: findFoodInfiniteQueryKey(options),
    },
  );
};

export const getFoodQueryKey = (options: Options<GetFoodData>) =>
  createQueryKey("getFood", options);

/**
 * Returns data on food for user
 */
export const getFoodOptions = (options: Options<GetFoodData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getFood({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getFoodQueryKey(options),
  });
};

export const getFoodInfiniteQueryKey = (
  options: Options<GetFoodData>,
): QueryKey<Options<GetFoodData>> => createQueryKey("getFood", options, true);

/**
 * Returns data on food for user
 */
export const getFoodInfiniteOptions = (options: Options<GetFoodData>) => {
  return infiniteQueryOptions<
    GetFoodResponse,
    AxiosError<GetFoodError>,
    InfiniteData<GetFoodResponse>,
    QueryKey<Options<GetFoodData>>,
    | number
    | Pick<
        QueryKey<Options<GetFoodData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetFoodData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getFood({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getFoodInfiniteQueryKey(options),
    },
  );
};

export const scanBarcodeQueryKey = (options?: Options<ScanBarcodeData>) =>
  createQueryKey("scanBarcode", options);

/**
 * Scans a barcode and returns data on food
 */
export const scanBarcodeOptions = (options?: Options<ScanBarcodeData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await scanBarcode({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: scanBarcodeQueryKey(options),
  });
};

/**
 * Scans a barcode and returns data on food
 */
export const scanBarcodeMutation = (
  options?: Partial<Options<ScanBarcodeData>>,
): UseMutationOptions<
  ScanBarcodeResponse,
  AxiosError<ScanBarcodeError>,
  Options<ScanBarcodeData>
> => {
  const mutationOptions: UseMutationOptions<
    ScanBarcodeResponse,
    AxiosError<ScanBarcodeError>,
    Options<ScanBarcodeData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await scanBarcode({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getOwnProfileQueryKey = (options?: Options<GetOwnProfileData>) =>
  createQueryKey("getOwnProfile", options);

/**
 * Returns data on user profile
 */
export const getOwnProfileOptions = (options?: Options<GetOwnProfileData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getOwnProfile({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getOwnProfileQueryKey(options),
  });
};

export const getSettingsQueryKey = (options?: Options<GetSettingsData>) =>
  createQueryKey("getSettings", options);

/**
 * Returns data on user settings & profile
 */
export const getSettingsOptions = (options?: Options<GetSettingsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getSettings({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getSettingsQueryKey(options),
  });
};

export const updateSettingsQueryKey = (options?: Options<UpdateSettingsData>) =>
  createQueryKey("updateSettings", options);

/**
 * Updates user settings & profile
 */
export const updateSettingsOptions = (
  options?: Options<UpdateSettingsData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await updateSettings({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: updateSettingsQueryKey(options),
  });
};

/**
 * Updates user settings & profile
 */
export const updateSettingsMutation = (
  options?: Partial<Options<UpdateSettingsData>>,
): UseMutationOptions<
  UpdateSettingsResponse,
  AxiosError<UpdateSettingsError>,
  Options<UpdateSettingsData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateSettingsResponse,
    AxiosError<UpdateSettingsError>,
    Options<UpdateSettingsData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await updateSettings({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getCrmUsersQueryKey = (options?: Options<GetCrmUsersData>) =>
  createQueryKey("getCrmUsers", options);

/**
 * Returns list of users
 */
export const getCrmUsersOptions = (options?: Options<GetCrmUsersData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getCrmUsers({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getCrmUsersQueryKey(options),
  });
};

export const getCrmUsersInfiniteQueryKey = (
  options?: Options<GetCrmUsersData>,
): QueryKey<Options<GetCrmUsersData>> =>
  createQueryKey("getCrmUsers", options, true);

/**
 * Returns list of users
 */
export const getCrmUsersInfiniteOptions = (
  options?: Options<GetCrmUsersData>,
) => {
  return infiniteQueryOptions<
    GetCrmUsersResponse,
    AxiosError<GetCrmUsersError>,
    InfiniteData<GetCrmUsersResponse>,
    QueryKey<Options<GetCrmUsersData>>,
    | number
    | Pick<
        QueryKey<Options<GetCrmUsersData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetCrmUsersData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getCrmUsers({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getCrmUsersInfiniteQueryKey(options),
    },
  );
};

export const getCrmManagersQueryKey = (options?: Options<GetCrmManagersData>) =>
  createQueryKey("getCrmManagers", options);

/**
 * Returns list of managers
 */
export const getCrmManagersOptions = (
  options?: Options<GetCrmManagersData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getCrmManagers({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getCrmManagersQueryKey(options),
  });
};

export const getCrmManagersInfiniteQueryKey = (
  options?: Options<GetCrmManagersData>,
): QueryKey<Options<GetCrmManagersData>> =>
  createQueryKey("getCrmManagers", options, true);

/**
 * Returns list of managers
 */
export const getCrmManagersInfiniteOptions = (
  options?: Options<GetCrmManagersData>,
) => {
  return infiniteQueryOptions<
    GetCrmManagersResponse,
    AxiosError<GetCrmManagersError>,
    InfiniteData<GetCrmManagersResponse>,
    QueryKey<Options<GetCrmManagersData>>,
    | number
    | Pick<
        QueryKey<Options<GetCrmManagersData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetCrmManagersData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getCrmManagers({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getCrmManagersInfiniteQueryKey(options),
    },
  );
};

export const managerLoginQueryKey = (options?: Options<ManagerLoginData>) =>
  createQueryKey("managerLogin", options);

/**
 * Logins a manager into CRM
 */
export const managerLoginOptions = (options?: Options<ManagerLoginData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await managerLogin({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: managerLoginQueryKey(options),
  });
};

/**
 * Logins a manager into CRM
 */
export const managerLoginMutation = (
  options?: Partial<Options<ManagerLoginData>>,
): UseMutationOptions<
  ManagerLoginResponse,
  AxiosError<ManagerLoginError>,
  Options<ManagerLoginData>
> => {
  const mutationOptions: UseMutationOptions<
    ManagerLoginResponse,
    AxiosError<ManagerLoginError>,
    Options<ManagerLoginData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await managerLogin({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getCrmTranslationsByIdQueryKey = (
  options: Options<GetCrmTranslationsByIdData>,
) => createQueryKey("getCrmTranslationsById", options);

/**
 * Returns translation
 */
export const getCrmTranslationsByIdOptions = (
  options: Options<GetCrmTranslationsByIdData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getCrmTranslationsById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getCrmTranslationsByIdQueryKey(options),
  });
};

/**
 * Updates translation
 */
export const patchCrmTranslationsByIdMutation = (
  options?: Partial<Options<PatchCrmTranslationsByIdData>>,
): UseMutationOptions<
  PatchCrmTranslationsByIdResponse,
  AxiosError<PatchCrmTranslationsByIdError>,
  Options<PatchCrmTranslationsByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    PatchCrmTranslationsByIdResponse,
    AxiosError<PatchCrmTranslationsByIdError>,
    Options<PatchCrmTranslationsByIdData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await patchCrmTranslationsById({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getCrmTranslationsQueryKey = (
  options?: Options<GetCrmTranslationsData>,
) => createQueryKey("getCrmTranslations", options);

/**
 * Returns list of translations
 */
export const getCrmTranslationsOptions = (
  options?: Options<GetCrmTranslationsData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getCrmTranslations({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getCrmTranslationsQueryKey(options),
  });
};

export const getCrmTranslationsInfiniteQueryKey = (
  options?: Options<GetCrmTranslationsData>,
): QueryKey<Options<GetCrmTranslationsData>> =>
  createQueryKey("getCrmTranslations", options, true);

/**
 * Returns list of translations
 */
export const getCrmTranslationsInfiniteOptions = (
  options?: Options<GetCrmTranslationsData>,
) => {
  return infiniteQueryOptions<
    GetCrmTranslationsResponse,
    AxiosError<GetCrmTranslationsError>,
    InfiniteData<GetCrmTranslationsResponse>,
    QueryKey<Options<GetCrmTranslationsData>>,
    | number
    | Pick<
        QueryKey<Options<GetCrmTranslationsData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetCrmTranslationsData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getCrmTranslations({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getCrmTranslationsInfiniteQueryKey(options),
    },
  );
};

export const getCrmExercisesByIdQueryKey = (
  options: Options<GetCrmExercisesByIdData>,
) => createQueryKey("getCrmExercisesById", options);

/**
 * Returns data on an exercise
 */
export const getCrmExercisesByIdOptions = (
  options: Options<GetCrmExercisesByIdData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getCrmExercisesById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getCrmExercisesByIdQueryKey(options),
  });
};

/**
 * Updates exercise
 */
export const patchCrmExercisesByIdMutation = (
  options?: Partial<Options<PatchCrmExercisesByIdData>>,
): UseMutationOptions<
  PatchCrmExercisesByIdResponse,
  AxiosError<PatchCrmExercisesByIdError>,
  Options<PatchCrmExercisesByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    PatchCrmExercisesByIdResponse,
    AxiosError<PatchCrmExercisesByIdError>,
    Options<PatchCrmExercisesByIdData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await patchCrmExercisesById({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getCrmExercisesQueryKey = (
  options?: Options<GetCrmExercisesData>,
) => createQueryKey("getCrmExercises", options);

/**
 * Returns data on exercises
 */
export const getCrmExercisesOptions = (
  options?: Options<GetCrmExercisesData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getCrmExercises({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getCrmExercisesQueryKey(options),
  });
};

export const getCrmExercisesInfiniteQueryKey = (
  options?: Options<GetCrmExercisesData>,
): QueryKey<Options<GetCrmExercisesData>> =>
  createQueryKey("getCrmExercises", options, true);

/**
 * Returns data on exercises
 */
export const getCrmExercisesInfiniteOptions = (
  options?: Options<GetCrmExercisesData>,
) => {
  return infiniteQueryOptions<
    GetCrmExercisesResponse,
    AxiosError<GetCrmExercisesError>,
    InfiniteData<GetCrmExercisesResponse>,
    QueryKey<Options<GetCrmExercisesData>>,
    | number
    | Pick<
        QueryKey<Options<GetCrmExercisesData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetCrmExercisesData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getCrmExercises({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getCrmExercisesInfiniteQueryKey(options),
    },
  );
};

export const getCrmImagesQueryKey = (options?: Options<GetCrmImagesData>) =>
  createQueryKey("getCrmImages", options);

/**
 * Returns data on images
 */
export const getCrmImagesOptions = (options?: Options<GetCrmImagesData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getCrmImages({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getCrmImagesQueryKey(options),
  });
};

export const getCrmImagesInfiniteQueryKey = (
  options?: Options<GetCrmImagesData>,
): QueryKey<Options<GetCrmImagesData>> =>
  createQueryKey("getCrmImages", options, true);

/**
 * Returns data on images
 */
export const getCrmImagesInfiniteOptions = (
  options?: Options<GetCrmImagesData>,
) => {
  return infiniteQueryOptions<
    GetCrmImagesResponse,
    AxiosError<GetCrmImagesError>,
    InfiniteData<GetCrmImagesResponse>,
    QueryKey<Options<GetCrmImagesData>>,
    | number
    | Pick<
        QueryKey<Options<GetCrmImagesData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetCrmImagesData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getCrmImages({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getCrmImagesInfiniteQueryKey(options),
    },
  );
};

/**
 * Deletes image
 */
export const deleteCrmImagesByIdMutation = (
  options?: Partial<Options<DeleteCrmImagesByIdData>>,
): UseMutationOptions<
  DeleteCrmImagesByIdResponse,
  AxiosError<DeleteCrmImagesByIdError>,
  Options<DeleteCrmImagesByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteCrmImagesByIdResponse,
    AxiosError<DeleteCrmImagesByIdError>,
    Options<DeleteCrmImagesByIdData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await deleteCrmImagesById({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};
