// This file is auto-generated by @hey-api/openapi-ts

import type {
  GetExercisesResponse,
  PostExercisesResponse,
  PutExercisesResponse,
  GetExercisesBuiltInResponse,
  GetExercisesByIdResponse,
  GetWorkoutsResponse,
  PostWorkoutsResponse,
  PutWorkoutsResponse,
  GetWorkoutsByIdResponse,
  PatchWorkoutsByIdResponse,
  GetWorkoutPlansResponse,
  PostWorkoutPlansResponse,
  GetWorkoutPlansByIdResponse,
  PatchWorkoutPlansByIdResponse,
  GetWorkoutTypesResponse,
  PostWorkoutTypesResponse,
  GetWorkoutTypesByIdResponse,
  PatchWorkoutTypesByIdResponse,
  PostWeightResponse,
  GetWeightByIdResponse,
  PatchWeightByIdResponse,
  GetArgusCheckinResponse,
  GetEntriesOwnResponse,
  GetEntriesByIdResponse,
  GetEntriesResponse,
  PutEntriesResponse,
  PostImagesResponse,
  GetImagesByIdResponse,
  PatchImagesByIdResponse,
  GetCrmManagersResponse,
  GetCrmTranslationsByIdResponse,
  PatchCrmTranslationsByIdResponse,
  GetCrmTranslationsResponse,
  GetCrmExercisesByIdResponse,
  GetCrmExercisesResponse,
  GetCrmImagesResponse,
} from "./types.gen";

const exerciseSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt);
  if (data.updatedAt) {
    data.updatedAt = new Date(data.updatedAt);
  }
  if (data.deletedAt) {
    data.deletedAt = new Date(data.deletedAt);
  }
  data.variations = data.variations.map((item: any) => {
    item.createdAt = new Date(item.createdAt);
    if (item.updatedAt) {
      item.updatedAt = new Date(item.updatedAt);
    }
    if (item.deletedAt) {
      item.deletedAt = new Date(item.deletedAt);
    }
    return item;
  });
  return data;
};

export const getExercisesResponseTransformer = async (
  data: any,
): Promise<GetExercisesResponse> => {
  data.items = data.items.map((item: any) => {
    return exerciseSchemaResponseTransformer(item);
  });
  return data;
};

export const postExercisesResponseTransformer = async (
  data: any,
): Promise<PostExercisesResponse> => {
  data = exerciseSchemaResponseTransformer(data);
  return data;
};

export const putExercisesResponseTransformer = async (
  data: any,
): Promise<PutExercisesResponse> => {
  data.items = data.items.map((item: any) => {
    return exerciseSchemaResponseTransformer(item);
  });
  return data;
};

export const getExercisesBuiltInResponseTransformer = async (
  data: any,
): Promise<GetExercisesBuiltInResponse> => {
  data.items = data.items.map((item: any) => {
    return exerciseSchemaResponseTransformer(item);
  });
  return data;
};

export const getExercisesByIdResponseTransformer = async (
  data: any,
): Promise<GetExercisesByIdResponse> => {
  data = exerciseSchemaResponseTransformer(data);
  return data;
};

const workoutExerciseSetSchemaResponseTransformer = (data: any) => {
  if (data.start) {
    data.start = new Date(data.start);
  }
  if (data.end) {
    data.end = new Date(data.end);
  }
  return data;
};

const workoutExerciseSchemaResponseTransformer = (data: any) => {
  data.exercise = exerciseSchemaResponseTransformer(data.exercise);
  data.sets = data.sets.map((item: any) => {
    return workoutExerciseSetSchemaResponseTransformer(item);
  });
  return data;
};

const workoutSchemaResponseTransformer = (data: any) => {
  data.start = new Date(data.start);
  if (data.end) {
    data.end = new Date(data.end);
  }
  data.createdAt = new Date(data.createdAt);
  if (data.updatedAt) {
    data.updatedAt = new Date(data.updatedAt);
  }
  if (data.deletedAt) {
    data.deletedAt = new Date(data.deletedAt);
  }
  data.exercises = data.exercises.map((item: any) => {
    return workoutExerciseSchemaResponseTransformer(item);
  });
  return data;
};

export const getWorkoutsResponseTransformer = async (
  data: any,
): Promise<GetWorkoutsResponse> => {
  data.items = data.items.map((item: any) => {
    return workoutSchemaResponseTransformer(item);
  });
  return data;
};

export const postWorkoutsResponseTransformer = async (
  data: any,
): Promise<PostWorkoutsResponse> => {
  data = workoutSchemaResponseTransformer(data);
  return data;
};

export const putWorkoutsResponseTransformer = async (
  data: any,
): Promise<PutWorkoutsResponse> => {
  data.items = data.items.map((item: any) => {
    return workoutSchemaResponseTransformer(item);
  });
  return data;
};

export const getWorkoutsByIdResponseTransformer = async (
  data: any,
): Promise<GetWorkoutsByIdResponse> => {
  data.item = workoutSchemaResponseTransformer(data.item);
  return data;
};

export const patchWorkoutsByIdResponseTransformer = async (
  data: any,
): Promise<PatchWorkoutsByIdResponse> => {
  data = workoutSchemaResponseTransformer(data);
  return data;
};

const workoutPlanSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt);
  if (data.updatedAt) {
    data.updatedAt = new Date(data.updatedAt);
  }
  if (data.deletedAt) {
    data.deletedAt = new Date(data.deletedAt);
  }
  return data;
};

export const getWorkoutPlansResponseTransformer = async (
  data: any,
): Promise<GetWorkoutPlansResponse> => {
  data.items = data.items.map((item: any) => {
    return workoutPlanSchemaResponseTransformer(item);
  });
  return data;
};

export const postWorkoutPlansResponseTransformer = async (
  data: any,
): Promise<PostWorkoutPlansResponse> => {
  data = workoutPlanSchemaResponseTransformer(data);
  return data;
};

export const getWorkoutPlansByIdResponseTransformer = async (
  data: any,
): Promise<GetWorkoutPlansByIdResponse> => {
  data = workoutPlanSchemaResponseTransformer(data);
  return data;
};

export const patchWorkoutPlansByIdResponseTransformer = async (
  data: any,
): Promise<PatchWorkoutPlansByIdResponse> => {
  data = workoutPlanSchemaResponseTransformer(data);
  return data;
};

const workoutTypeExerciseSchemaResponseTransformer = (data: any) => {
  data.exercise = exerciseSchemaResponseTransformer(data.exercise);
  return data;
};

const workoutTypeSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt);
  if (data.updatedAt) {
    data.updatedAt = new Date(data.updatedAt);
  }
  if (data.deletedAt) {
    data.deletedAt = new Date(data.deletedAt);
  }
  data.exercises = data.exercises.map((item: any) => {
    return workoutTypeExerciseSchemaResponseTransformer(item);
  });
  return data;
};

export const getWorkoutTypesResponseTransformer = async (
  data: any,
): Promise<GetWorkoutTypesResponse> => {
  data.items = data.items.map((item: any) => {
    return workoutTypeSchemaResponseTransformer(item);
  });
  return data;
};

export const postWorkoutTypesResponseTransformer = async (
  data: any,
): Promise<PostWorkoutTypesResponse> => {
  data = workoutTypeSchemaResponseTransformer(data);
  return data;
};

export const getWorkoutTypesByIdResponseTransformer = async (
  data: any,
): Promise<GetWorkoutTypesByIdResponse> => {
  data = workoutTypeSchemaResponseTransformer(data);
  return data;
};

export const patchWorkoutTypesByIdResponseTransformer = async (
  data: any,
): Promise<PatchWorkoutTypesByIdResponse> => {
  data = workoutTypeSchemaResponseTransformer(data);
  return data;
};

const weightSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt);
  if (data.updatedAt) {
    data.updatedAt = new Date(data.updatedAt);
  }
  if (data.deletedAt) {
    data.deletedAt = new Date(data.deletedAt);
  }
  return data;
};

export const postWeightResponseTransformer = async (
  data: any,
): Promise<PostWeightResponse> => {
  data = weightSchemaResponseTransformer(data);
  return data;
};

export const getWeightByIdResponseTransformer = async (
  data: any,
): Promise<GetWeightByIdResponse> => {
  data = weightSchemaResponseTransformer(data);
  return data;
};

export const patchWeightByIdResponseTransformer = async (
  data: any,
): Promise<PatchWeightByIdResponse> => {
  data = weightSchemaResponseTransformer(data);
  return data;
};

export const getArgusCheckinResponseTransformer = async (
  data: any,
): Promise<GetArgusCheckinResponse> => {
  data.items = data.items.map((item: any) => {
    item.createdAt = new Date(item.createdAt);
    if (item.updatedAt) {
      item.updatedAt = new Date(item.updatedAt);
    }
    return item;
  });
  return data;
};

const imageSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt);
  if (data.updatedAt) {
    data.updatedAt = new Date(data.updatedAt);
  }
  if (data.deletedAt) {
    data.deletedAt = new Date(data.deletedAt);
  }
  return data;
};

const entrySchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt);
  if (data.updatedAt) {
    data.updatedAt = new Date(data.updatedAt);
  }
  if (data.deletedAt) {
    data.deletedAt = new Date(data.deletedAt);
  }
  if (data.weight) {
    data.weight = weightSchemaResponseTransformer(data.weight);
  }
  if (data.workout) {
    data.workout = workoutSchemaResponseTransformer(data.workout);
  }
  if (data.image) {
    data.image = imageSchemaResponseTransformer(data.image);
  }
  return data;
};

export const getEntriesOwnResponseTransformer = async (
  data: any,
): Promise<GetEntriesOwnResponse> => {
  data.items = data.items.map((item: any) => {
    return entrySchemaResponseTransformer(item);
  });
  return data;
};

export const getEntriesByIdResponseTransformer = async (
  data: any,
): Promise<GetEntriesByIdResponse> => {
  data = entrySchemaResponseTransformer(data);
  return data;
};

export const getEntriesResponseTransformer = async (
  data: any,
): Promise<GetEntriesResponse> => {
  data.items = data.items.map((item: any) => {
    return entrySchemaResponseTransformer(item);
  });
  return data;
};

export const putEntriesResponseTransformer = async (
  data: any,
): Promise<PutEntriesResponse> => {
  data.items = data.items.map((item: any) => {
    return entrySchemaResponseTransformer(item);
  });
  return data;
};

export const postImagesResponseTransformer = async (
  data: any,
): Promise<PostImagesResponse> => {
  data.createdAt = new Date(data.createdAt);
  if (data.updatedAt) {
    data.updatedAt = new Date(data.updatedAt);
  }
  if (data.deletedAt) {
    data.deletedAt = new Date(data.deletedAt);
  }
  if (data.weight) {
    data.weight = weightSchemaResponseTransformer(data.weight);
  }
  if (data.workout) {
    data.workout = workoutSchemaResponseTransformer(data.workout);
  }
  data.image = imageSchemaResponseTransformer(data.image);
  return data;
};

export const getImagesByIdResponseTransformer = async (
  data: any,
): Promise<GetImagesByIdResponse> => {
  data.createdAt = new Date(data.createdAt);
  if (data.updatedAt) {
    data.updatedAt = new Date(data.updatedAt);
  }
  if (data.deletedAt) {
    data.deletedAt = new Date(data.deletedAt);
  }
  if (data.weight) {
    data.weight = weightSchemaResponseTransformer(data.weight);
  }
  if (data.workout) {
    data.workout = workoutSchemaResponseTransformer(data.workout);
  }
  data.image = imageSchemaResponseTransformer(data.image);
  return data;
};

export const patchImagesByIdResponseTransformer = async (
  data: any,
): Promise<PatchImagesByIdResponse> => {
  data.createdAt = new Date(data.createdAt);
  if (data.updatedAt) {
    data.updatedAt = new Date(data.updatedAt);
  }
  if (data.deletedAt) {
    data.deletedAt = new Date(data.deletedAt);
  }
  if (data.weight) {
    data.weight = weightSchemaResponseTransformer(data.weight);
  }
  if (data.workout) {
    data.workout = workoutSchemaResponseTransformer(data.workout);
  }
  data.image = imageSchemaResponseTransformer(data.image);
  return data;
};

const managerSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt);
  if (data.updatedAt) {
    data.updatedAt = new Date(data.updatedAt);
  }
  if (data.deletedAt) {
    data.deletedAt = new Date(data.deletedAt);
  }
  return data;
};

export const getCrmManagersResponseTransformer = async (
  data: any,
): Promise<GetCrmManagersResponse> => {
  data.items = data.items.map((item: any) => {
    return managerSchemaResponseTransformer(item);
  });
  return data;
};

const translationSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt);
  if (data.updatedAt) {
    data.updatedAt = new Date(data.updatedAt);
  }
  if (data.deletedAt) {
    data.deletedAt = new Date(data.deletedAt);
  }
  return data;
};

export const getCrmTranslationsByIdResponseTransformer = async (
  data: any,
): Promise<GetCrmTranslationsByIdResponse> => {
  data = translationSchemaResponseTransformer(data);
  return data;
};

export const patchCrmTranslationsByIdResponseTransformer = async (
  data: any,
): Promise<PatchCrmTranslationsByIdResponse> => {
  data = translationSchemaResponseTransformer(data);
  return data;
};

export const getCrmTranslationsResponseTransformer = async (
  data: any,
): Promise<GetCrmTranslationsResponse> => {
  data.items = data.items.map((item: any) => {
    return translationSchemaResponseTransformer(item);
  });
  return data;
};

export const getCrmExercisesByIdResponseTransformer = async (
  data: any,
): Promise<GetCrmExercisesByIdResponse> => {
  data = exerciseSchemaResponseTransformer(data);
  return data;
};

export const getCrmExercisesResponseTransformer = async (
  data: any,
): Promise<GetCrmExercisesResponse> => {
  data.items = data.items.map((item: any) => {
    return exerciseSchemaResponseTransformer(item);
  });
  return data;
};

export const getCrmImagesResponseTransformer = async (
  data: any,
): Promise<GetCrmImagesResponse> => {
  data.items = data.items.map((item: any) => {
    return imageSchemaResponseTransformer(item);
  });
  return data;
};
