// This file is auto-generated by @hey-api/openapi-ts

import type {
  GetExercisesResponse,
  PostExercisesResponse,
  PutExercisesResponse,
  GetExercisesBuiltInResponse,
  GetExercisesByIdResponse,
  GetWorkoutsResponse,
  PostWorkoutsResponse,
  PutWorkoutsResponse,
  GetWorkoutsByIdResponse,
  PatchWorkoutsByIdResponse,
  GetWorkoutPlansResponse,
  PostWorkoutPlansResponse,
  GetWorkoutPlansByIdResponse,
  PatchWorkoutPlansByIdResponse,
  GetWorkoutTypesResponse,
  PostWorkoutTypesResponse,
  GetWorkoutTypesByIdResponse,
  PatchWorkoutTypesByIdResponse,
  PostWeightResponse,
  GetWeightByIdResponse,
  PatchWeightByIdResponse,
  GetArgusCheckinResponse,
  GetEntriesOwnResponse,
  GetEntriesByIdResponse,
  GetEntriesResponse,
  PutEntriesResponse,
  GetEntriesOwnDatesResponse,
  PostPostsResponse,
  GetPostsByIdResponse,
  PatchPostsByIdResponse,
  GetFoodListResponse,
  UpsertFoodResponse,
  UpsertFoodsResponse,
  GetFoodResponse,
  GetOwnProfileResponse,
  GetSettingsResponse,
  UpdateSettingsResponse,
  GetCrmManagersResponse,
  GetCrmTranslationsByIdResponse,
  PatchCrmTranslationsByIdResponse,
  GetCrmTranslationsResponse,
  GetCrmExercisesByIdResponse,
  GetCrmExercisesResponse,
  GetCrmImagesResponse,
} from "./types.gen";

const exerciseSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt);
  if (data.updatedAt) {
    data.updatedAt = new Date(data.updatedAt);
  }
  if (data.deletedAt) {
    data.deletedAt = new Date(data.deletedAt);
  }
  data.variations = data.variations.map((item: any) => {
    item.createdAt = new Date(item.createdAt);
    if (item.updatedAt) {
      item.updatedAt = new Date(item.updatedAt);
    }
    if (item.deletedAt) {
      item.deletedAt = new Date(item.deletedAt);
    }
    return item;
  });
  return data;
};

export const getExercisesResponseTransformer = async (
  data: any,
): Promise<GetExercisesResponse> => {
  data.items = data.items.map((item: any) => {
    return exerciseSchemaResponseTransformer(item);
  });
  return data;
};

export const postExercisesResponseTransformer = async (
  data: any,
): Promise<PostExercisesResponse> => {
  data = exerciseSchemaResponseTransformer(data);
  return data;
};

export const putExercisesResponseTransformer = async (
  data: any,
): Promise<PutExercisesResponse> => {
  data.items = data.items.map((item: any) => {
    return exerciseSchemaResponseTransformer(item);
  });
  return data;
};

export const getExercisesBuiltInResponseTransformer = async (
  data: any,
): Promise<GetExercisesBuiltInResponse> => {
  data.items = data.items.map((item: any) => {
    return exerciseSchemaResponseTransformer(item);
  });
  return data;
};

export const getExercisesByIdResponseTransformer = async (
  data: any,
): Promise<GetExercisesByIdResponse> => {
  data = exerciseSchemaResponseTransformer(data);
  return data;
};

const workoutExerciseSetSchemaResponseTransformer = (data: any) => {
  if (data.start) {
    data.start = new Date(data.start);
  }
  if (data.end) {
    data.end = new Date(data.end);
  }
  return data;
};

const workoutExerciseSchemaResponseTransformer = (data: any) => {
  data.exercise = exerciseSchemaResponseTransformer(data.exercise);
  data.sets = data.sets.map((item: any) => {
    return workoutExerciseSetSchemaResponseTransformer(item);
  });
  return data;
};

const workoutSchemaResponseTransformer = (data: any) => {
  data.start = new Date(data.start);
  if (data.end) {
    data.end = new Date(data.end);
  }
  data.createdAt = new Date(data.createdAt);
  if (data.updatedAt) {
    data.updatedAt = new Date(data.updatedAt);
  }
  if (data.deletedAt) {
    data.deletedAt = new Date(data.deletedAt);
  }
  data.exercises = data.exercises.map((item: any) => {
    return workoutExerciseSchemaResponseTransformer(item);
  });
  return data;
};

export const getWorkoutsResponseTransformer = async (
  data: any,
): Promise<GetWorkoutsResponse> => {
  data.items = data.items.map((item: any) => {
    return workoutSchemaResponseTransformer(item);
  });
  return data;
};

export const postWorkoutsResponseTransformer = async (
  data: any,
): Promise<PostWorkoutsResponse> => {
  data = workoutSchemaResponseTransformer(data);
  return data;
};

export const putWorkoutsResponseTransformer = async (
  data: any,
): Promise<PutWorkoutsResponse> => {
  data.items = data.items.map((item: any) => {
    return workoutSchemaResponseTransformer(item);
  });
  return data;
};

export const getWorkoutsByIdResponseTransformer = async (
  data: any,
): Promise<GetWorkoutsByIdResponse> => {
  data.item = workoutSchemaResponseTransformer(data.item);
  return data;
};

export const patchWorkoutsByIdResponseTransformer = async (
  data: any,
): Promise<PatchWorkoutsByIdResponse> => {
  data = workoutSchemaResponseTransformer(data);
  return data;
};

const workoutPlanSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt);
  if (data.updatedAt) {
    data.updatedAt = new Date(data.updatedAt);
  }
  if (data.deletedAt) {
    data.deletedAt = new Date(data.deletedAt);
  }
  return data;
};

export const getWorkoutPlansResponseTransformer = async (
  data: any,
): Promise<GetWorkoutPlansResponse> => {
  data.items = data.items.map((item: any) => {
    return workoutPlanSchemaResponseTransformer(item);
  });
  return data;
};

export const postWorkoutPlansResponseTransformer = async (
  data: any,
): Promise<PostWorkoutPlansResponse> => {
  data = workoutPlanSchemaResponseTransformer(data);
  return data;
};

export const getWorkoutPlansByIdResponseTransformer = async (
  data: any,
): Promise<GetWorkoutPlansByIdResponse> => {
  data = workoutPlanSchemaResponseTransformer(data);
  return data;
};

export const patchWorkoutPlansByIdResponseTransformer = async (
  data: any,
): Promise<PatchWorkoutPlansByIdResponse> => {
  data = workoutPlanSchemaResponseTransformer(data);
  return data;
};

const workoutTypeExerciseSchemaResponseTransformer = (data: any) => {
  data.exercise = exerciseSchemaResponseTransformer(data.exercise);
  return data;
};

const workoutTypeSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt);
  if (data.updatedAt) {
    data.updatedAt = new Date(data.updatedAt);
  }
  if (data.deletedAt) {
    data.deletedAt = new Date(data.deletedAt);
  }
  data.exercises = data.exercises.map((item: any) => {
    return workoutTypeExerciseSchemaResponseTransformer(item);
  });
  return data;
};

export const getWorkoutTypesResponseTransformer = async (
  data: any,
): Promise<GetWorkoutTypesResponse> => {
  data.items = data.items.map((item: any) => {
    return workoutTypeSchemaResponseTransformer(item);
  });
  return data;
};

export const postWorkoutTypesResponseTransformer = async (
  data: any,
): Promise<PostWorkoutTypesResponse> => {
  data = workoutTypeSchemaResponseTransformer(data);
  return data;
};

export const getWorkoutTypesByIdResponseTransformer = async (
  data: any,
): Promise<GetWorkoutTypesByIdResponse> => {
  data = workoutTypeSchemaResponseTransformer(data);
  return data;
};

export const patchWorkoutTypesByIdResponseTransformer = async (
  data: any,
): Promise<PatchWorkoutTypesByIdResponse> => {
  data = workoutTypeSchemaResponseTransformer(data);
  return data;
};

const weightSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt);
  if (data.updatedAt) {
    data.updatedAt = new Date(data.updatedAt);
  }
  if (data.deletedAt) {
    data.deletedAt = new Date(data.deletedAt);
  }
  data.history = data.history.map((item: any) => {
    item.createdAt = new Date(item.createdAt);
    if (item.updatedAt) {
      item.updatedAt = new Date(item.updatedAt);
    }
    if (item.deletedAt) {
      item.deletedAt = new Date(item.deletedAt);
    }
    return item;
  });
  return data;
};

export const postWeightResponseTransformer = async (
  data: any,
): Promise<PostWeightResponse> => {
  data = weightSchemaResponseTransformer(data);
  return data;
};

export const getWeightByIdResponseTransformer = async (
  data: any,
): Promise<GetWeightByIdResponse> => {
  data = weightSchemaResponseTransformer(data);
  return data;
};

export const patchWeightByIdResponseTransformer = async (
  data: any,
): Promise<PatchWeightByIdResponse> => {
  data = weightSchemaResponseTransformer(data);
  return data;
};

export const getArgusCheckinResponseTransformer = async (
  data: any,
): Promise<GetArgusCheckinResponse> => {
  data.items = data.items.map((item: any) => {
    item.createdAt = new Date(item.createdAt);
    if (item.updatedAt) {
      item.updatedAt = new Date(item.updatedAt);
    }
    return item;
  });
  return data;
};

const outdoorRunSchemaResponseTransformer = (data: any) => {
  data.start = new Date(data.start);
  data.end = new Date(data.end);
  return data;
};

const outdoorWalkSchemaResponseTransformer = (data: any) => {
  data = outdoorRunSchemaResponseTransformer(data);
  return data;
};

const foodSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt);
  if (data.updatedAt) {
    data.updatedAt = new Date(data.updatedAt);
  }
  if (data.deletedAt) {
    data.deletedAt = new Date(data.deletedAt);
  }
  data.components = data.components.map((item: any) => {
    return foodComponentSchemaResponseTransformer(item);
  });
  return data;
};

const foodComponentSchemaResponseTransformer = (data: any) => {
  data.food = foodSchemaResponseTransformer(data.food);
  return data;
};

const mealFoodComponentSchemaResponseTransformer = (data: any) => {
  data.food.createdAt = new Date(data.food.createdAt);
  if (data.food.updatedAt) {
    data.food.updatedAt = new Date(data.food.updatedAt);
  }
  if (data.food.deletedAt) {
    data.food.deletedAt = new Date(data.food.deletedAt);
  }
  data.food.components = data.food.components.map((item: any) => {
    return foodComponentSchemaResponseTransformer(item);
  });
  return data;
};

const mealSchemaResponseTransformer = (data: any) => {
  data.food = data.food.map((item: any) => {
    return mealFoodComponentSchemaResponseTransformer(item);
  });
  return data;
};

const calorieGoalSchemaResponseTransformer = (data: any) => {
  data.start = new Date(data.start);
  if (data.end) {
    data.end = new Date(data.end);
  }
  return data;
};

const entrySchemaResponseTransformer = (data: any) => {
  data.time = new Date(data.time);
  data.createdAt = new Date(data.createdAt);
  if (data.updatedAt) {
    data.updatedAt = new Date(data.updatedAt);
  }
  if (data.deletedAt) {
    data.deletedAt = new Date(data.deletedAt);
  }
  if (data.weight) {
    data.weight = weightSchemaResponseTransformer(data.weight);
  }
  if (data.workout) {
    data.workout = workoutSchemaResponseTransformer(data.workout);
  }
  if (data.outdoorRun) {
    data.outdoorRun = outdoorRunSchemaResponseTransformer(data.outdoorRun);
  }
  if (data.outdoorWalk) {
    data.outdoorWalk = outdoorWalkSchemaResponseTransformer(data.outdoorWalk);
  }
  if (data.meal) {
    data.meal = mealSchemaResponseTransformer(data.meal);
  }
  if (data.calorieGoal) {
    data.calorieGoal = calorieGoalSchemaResponseTransformer(data.calorieGoal);
  }
  return data;
};

export const getEntriesOwnResponseTransformer = async (
  data: any,
): Promise<GetEntriesOwnResponse> => {
  data.items = data.items.map((item: any) => {
    return entrySchemaResponseTransformer(item);
  });
  return data;
};

export const getEntriesByIdResponseTransformer = async (
  data: any,
): Promise<GetEntriesByIdResponse> => {
  data = entrySchemaResponseTransformer(data);
  return data;
};

const reducedOutdoorRunSchemaResponseTransformer = (data: any) => {
  data.start = new Date(data.start);
  data.end = new Date(data.end);
  return data;
};

const reducedOutdoorWalkSchemaResponseTransformer = (data: any) => {
  data.start = new Date(data.start);
  data.end = new Date(data.end);
  return data;
};

const feedEntrySchemaResponseTransformer = (data: any) => {
  data.time = new Date(data.time);
  data.createdAt = new Date(data.createdAt);
  if (data.updatedAt) {
    data.updatedAt = new Date(data.updatedAt);
  }
  if (data.deletedAt) {
    data.deletedAt = new Date(data.deletedAt);
  }
  if (data.weight) {
    data.weight = weightSchemaResponseTransformer(data.weight);
  }
  if (data.workout) {
    data.workout = workoutSchemaResponseTransformer(data.workout);
  }
  if (data.outdoorRun) {
    data.outdoorRun = reducedOutdoorRunSchemaResponseTransformer(
      data.outdoorRun,
    );
  }
  if (data.outdoorWalk) {
    data.outdoorWalk = reducedOutdoorWalkSchemaResponseTransformer(
      data.outdoorWalk,
    );
  }
  if (data.meal) {
    data.meal = mealSchemaResponseTransformer(data.meal);
  }
  if (data.calorieGoal) {
    data.calorieGoal = calorieGoalSchemaResponseTransformer(data.calorieGoal);
  }
  return data;
};

export const getEntriesResponseTransformer = async (
  data: any,
): Promise<GetEntriesResponse> => {
  data.items = data.items.map((item: any) => {
    return feedEntrySchemaResponseTransformer(item);
  });
  return data;
};

export const putEntriesResponseTransformer = async (
  data: any,
): Promise<PutEntriesResponse> => {
  data.items = data.items.map((item: any) => {
    return entrySchemaResponseTransformer(item);
  });
  return data;
};

const dateListSchemaResponseTransformer = (data: any) => {
  data = data.map((item: any) => {
    item.value = new Date(item.value);
    return item;
  });
  return data;
};

export const getEntriesOwnDatesResponseTransformer = async (
  data: any,
): Promise<GetEntriesOwnDatesResponse> => {
  data = dateListSchemaResponseTransformer(data);
  return data;
};

const postEntrySchemaResponseTransformer = (data: any) => {
  data.time = new Date(data.time);
  data.createdAt = new Date(data.createdAt);
  if (data.updatedAt) {
    data.updatedAt = new Date(data.updatedAt);
  }
  if (data.deletedAt) {
    data.deletedAt = new Date(data.deletedAt);
  }
  if (data.weight) {
    data.weight = weightSchemaResponseTransformer(data.weight);
  }
  if (data.workout) {
    data.workout = workoutSchemaResponseTransformer(data.workout);
  }
  if (data.outdoorRun) {
    data.outdoorRun = outdoorRunSchemaResponseTransformer(data.outdoorRun);
  }
  if (data.outdoorWalk) {
    data.outdoorWalk = outdoorWalkSchemaResponseTransformer(data.outdoorWalk);
  }
  if (data.meal) {
    data.meal = mealSchemaResponseTransformer(data.meal);
  }
  if (data.calorieGoal) {
    data.calorieGoal = calorieGoalSchemaResponseTransformer(data.calorieGoal);
  }
  return data;
};

export const postPostsResponseTransformer = async (
  data: any,
): Promise<PostPostsResponse> => {
  data = postEntrySchemaResponseTransformer(data);
  return data;
};

export const getPostsByIdResponseTransformer = async (
  data: any,
): Promise<GetPostsByIdResponse> => {
  data = postEntrySchemaResponseTransformer(data);
  return data;
};

export const patchPostsByIdResponseTransformer = async (
  data: any,
): Promise<PatchPostsByIdResponse> => {
  data = postEntrySchemaResponseTransformer(data);
  return data;
};

export const getFoodListResponseTransformer = async (
  data: any,
): Promise<GetFoodListResponse> => {
  data.items = data.items.map((item: any) => {
    return foodSchemaResponseTransformer(item);
  });
  return data;
};

export const upsertFoodResponseTransformer = async (
  data: any,
): Promise<UpsertFoodResponse> => {
  data = foodSchemaResponseTransformer(data);
  return data;
};

export const upsertFoodsResponseTransformer = async (
  data: any,
): Promise<UpsertFoodsResponse> => {
  data = data.map((item: any) => {
    return foodSchemaResponseTransformer(item);
  });
  return data;
};

export const getFoodResponseTransformer = async (
  data: any,
): Promise<GetFoodResponse> => {
  data = foodSchemaResponseTransformer(data);
  return data;
};

const goalSchemaResponseTransformer = (data: any) => {
  if (data.calorie) {
    data.calorie = calorieGoalSchemaResponseTransformer(data.calorie);
  }
  return data;
};

const consumedCaloriesHistorySchemaResponseTransformer = (data: any) => {
  data.data = data.data.map((item: any) => {
    item.date = new Date(item.date);
    return item;
  });
  return data;
};

const profileSchemaResponseTransformer = (data: any) => {
  data.goals = data.goals.map((item: any) => {
    return goalSchemaResponseTransformer(item);
  });
  data.consumedCaloriesHistory =
    consumedCaloriesHistorySchemaResponseTransformer(
      data.consumedCaloriesHistory,
    );
  return data;
};

export const getOwnProfileResponseTransformer = async (
  data: any,
): Promise<GetOwnProfileResponse> => {
  data = profileSchemaResponseTransformer(data);
  return data;
};

const settingsSchemaResponseTransformer = (data: any) => {
  data.birthDate = new Date(data.birthDate);
  return data;
};

export const getSettingsResponseTransformer = async (
  data: any,
): Promise<GetSettingsResponse> => {
  data = settingsSchemaResponseTransformer(data);
  return data;
};

export const updateSettingsResponseTransformer = async (
  data: any,
): Promise<UpdateSettingsResponse> => {
  data = settingsSchemaResponseTransformer(data);
  return data;
};

const managerSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt);
  if (data.updatedAt) {
    data.updatedAt = new Date(data.updatedAt);
  }
  if (data.deletedAt) {
    data.deletedAt = new Date(data.deletedAt);
  }
  return data;
};

export const getCrmManagersResponseTransformer = async (
  data: any,
): Promise<GetCrmManagersResponse> => {
  data.items = data.items.map((item: any) => {
    return managerSchemaResponseTransformer(item);
  });
  return data;
};

const translationSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt);
  if (data.updatedAt) {
    data.updatedAt = new Date(data.updatedAt);
  }
  if (data.deletedAt) {
    data.deletedAt = new Date(data.deletedAt);
  }
  return data;
};

export const getCrmTranslationsByIdResponseTransformer = async (
  data: any,
): Promise<GetCrmTranslationsByIdResponse> => {
  data = translationSchemaResponseTransformer(data);
  return data;
};

export const patchCrmTranslationsByIdResponseTransformer = async (
  data: any,
): Promise<PatchCrmTranslationsByIdResponse> => {
  data = translationSchemaResponseTransformer(data);
  return data;
};

export const getCrmTranslationsResponseTransformer = async (
  data: any,
): Promise<GetCrmTranslationsResponse> => {
  data.items = data.items.map((item: any) => {
    return translationSchemaResponseTransformer(item);
  });
  return data;
};

export const getCrmExercisesByIdResponseTransformer = async (
  data: any,
): Promise<GetCrmExercisesByIdResponse> => {
  data = exerciseSchemaResponseTransformer(data);
  return data;
};

export const getCrmExercisesResponseTransformer = async (
  data: any,
): Promise<GetCrmExercisesResponse> => {
  data.items = data.items.map((item: any) => {
    return exerciseSchemaResponseTransformer(item);
  });
  return data;
};

const managedImageSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt);
  if (data.updatedAt) {
    data.updatedAt = new Date(data.updatedAt);
  }
  if (data.deletedAt) {
    data.deletedAt = new Date(data.deletedAt);
  }
  return data;
};

export const getCrmImagesResponseTransformer = async (
  data: any,
): Promise<GetCrmImagesResponse> => {
  data.items = data.items.map((item: any) => {
    return managedImageSchemaResponseTransformer(item);
  });
  return data;
};
