// This file is auto-generated by @hey-api/openapi-ts

import type {
  GetExercisesResponse,
  GetExercisesByIdResponse,
  GetWorkoutsResponse,
  GetWorkoutsByIdResponse,
  GetEntriesResponse,
} from "./types.gen";

const exerciseSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt);
  if (data.updatedAt) {
    data.updatedAt = new Date(data.updatedAt);
  }
  return data;
};

export const getExercisesResponseTransformer = async (
  data: any,
): Promise<GetExercisesResponse> => {
  data.items = data.items.map((item: any) => {
    return exerciseSchemaResponseTransformer(item);
  });
  return data;
};

export const getExercisesByIdResponseTransformer = async (
  data: any,
): Promise<GetExercisesByIdResponse> => {
  data.item = exerciseSchemaResponseTransformer(data.item);
  return data;
};

const exerciseSetSchemaResponseTransformer = (data: any) => {
  data.start = new Date(data.start);
  data.end = new Date(data.end);
  data.createdAt = new Date(data.createdAt);
  if (data.updatedAt) {
    data.updatedAt = new Date(data.updatedAt);
  }
  data.exercise = exerciseSchemaResponseTransformer(data.exercise);
  return data;
};

const workoutSchemaResponseTransformer = (data: any) => {
  data.start = new Date(data.start);
  data.end = new Date(data.end);
  data.createdAt = new Date(data.createdAt);
  if (data.updatedAt) {
    data.updatedAt = new Date(data.updatedAt);
  }
  data.sets = data.sets.map((item: any) => {
    return exerciseSetSchemaResponseTransformer(item);
  });
  return data;
};

export const getWorkoutsResponseTransformer = async (
  data: any,
): Promise<GetWorkoutsResponse> => {
  data.items = data.items.map((item: any) => {
    return workoutSchemaResponseTransformer(item);
  });
  return data;
};

export const getWorkoutsByIdResponseTransformer = async (
  data: any,
): Promise<GetWorkoutsByIdResponse> => {
  data.item = workoutSchemaResponseTransformer(data.item);
  return data;
};

export const getEntriesResponseTransformer = async (
  data: any,
): Promise<GetEntriesResponse> => {
  data.items = data.items.map((item: any) => {
    item.createdAt = new Date(item.createdAt);
    if (item.updatedAt) {
      item.updatedAt = new Date(item.updatedAt);
    }
    return item;
  });
  return data;
};
