ALTER TABLE "gym_tracker"."exercises" ALTER COLUMN "id" SET GENERATED BY DEFAULT;--> statement-breakpoint
ALTER TABLE "gym_tracker"."workout_exercise_sets" ALTER COLUMN "id" SET GENERATED BY DEFAULT;--> statement-breakpoint
ALTER TABLE "gym_tracker"."workout_exercises" ALTER COLUMN "id" SET GENERATED BY DEFAULT;--> statement-breakpoint
ALTER TABLE "gym_tracker"."workouts" ALTER COLUMN "id" SET GENERATED BY DEFAULT;