CREATE TYPE "gym_tracker"."EntryType" AS ENUM('Workout', 'Weight');--> statement-breakpoint
CREATE TYPE "gym_tracker"."EntryVisibility" AS ENUM('Public', 'Private');--> statement-breakpoint
CREATE TABLE "gym_tracker"."entries" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "gym_tracker"."entry_id_seq_alt" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"type" "gym_tracker"."EntryType" NOT NULL,
	"userId" integer NOT NULL,
	"workoutId" integer,
	"weightId" integer,
	"visibility" "gym_tracker"."EntryVisibility" NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone,
	"deletedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "gym_tracker"."entries" ADD CONSTRAINT "entries_userId_users_id_fk" FOREIGN KEY ("userId") REFERENCES "gym_tracker"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "gym_tracker"."entries" ADD CONSTRAINT "entries_workoutId_workouts_id_fk" FOREIGN KEY ("workoutId") REFERENCES "gym_tracker"."workouts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "gym_tracker"."entries" ADD CONSTRAINT "entries_weightId_weight_id_fk" FOREIGN KEY ("weightId") REFERENCES "gym_tracker"."weight"("id") ON DELETE no action ON UPDATE no action;