CREATE TABLE "gym_tracker"."workout_plan" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "gym_tracker"."workout_plan_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar,
	"description" text,
	"userId" integer NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone,
	"deletedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "gym_tracker"."workout_type_exercise_sets" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "gym_tracker"."workout_type_exercise_sets_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"reps" integer,
	"exerciseId" integer NOT NULL,
	"workoutTypeId" integer NOT NULL,
	"userId" integer NOT NULL,
	"workoutTypeExerciseId" integer NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone,
	"deletedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "gym_tracker"."workout_type_exercise" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "gym_tracker"."workout_type_exercise_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" integer NOT NULL,
	"index" integer NOT NULL,
	"workoutTypeId" integer NOT NULL,
	"exerciseId" integer NOT NULL,
	"description" text,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone,
	"deletedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "gym_tracker"."workout_type" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "gym_tracker"."workout_type_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" integer NOT NULL,
	"planIndex" integer,
	"planId" integer,
	"name" varchar,
	"description" text,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone,
	"deletedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "gym_tracker"."workout_plan" ADD CONSTRAINT "workout_plan_userId_users_id_fk" FOREIGN KEY ("userId") REFERENCES "gym_tracker"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "gym_tracker"."workout_type_exercise_sets" ADD CONSTRAINT "workout_type_exercise_sets_exerciseId_exercises_id_fk" FOREIGN KEY ("exerciseId") REFERENCES "gym_tracker"."exercises"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "gym_tracker"."workout_type_exercise_sets" ADD CONSTRAINT "workout_type_exercise_sets_workoutTypeId_workout_type_id_fk" FOREIGN KEY ("workoutTypeId") REFERENCES "gym_tracker"."workout_type"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "gym_tracker"."workout_type_exercise_sets" ADD CONSTRAINT "workout_type_exercise_sets_userId_users_id_fk" FOREIGN KEY ("userId") REFERENCES "gym_tracker"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "gym_tracker"."workout_type_exercise_sets" ADD CONSTRAINT "workout_type_exercise_sets_workoutTypeExerciseId_workout_type_exercise_id_fk" FOREIGN KEY ("workoutTypeExerciseId") REFERENCES "gym_tracker"."workout_type_exercise"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "gym_tracker"."workout_type_exercise" ADD CONSTRAINT "workout_type_exercise_userId_users_id_fk" FOREIGN KEY ("userId") REFERENCES "gym_tracker"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "gym_tracker"."workout_type_exercise" ADD CONSTRAINT "workout_type_exercise_workoutTypeId_workout_type_id_fk" FOREIGN KEY ("workoutTypeId") REFERENCES "gym_tracker"."workout_type"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "gym_tracker"."workout_type_exercise" ADD CONSTRAINT "workout_type_exercise_exerciseId_exercises_id_fk" FOREIGN KEY ("exerciseId") REFERENCES "gym_tracker"."exercises"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "gym_tracker"."workout_type" ADD CONSTRAINT "workout_type_userId_users_id_fk" FOREIGN KEY ("userId") REFERENCES "gym_tracker"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "gym_tracker"."workout_type" ADD CONSTRAINT "workout_type_planId_workout_plan_id_fk" FOREIGN KEY ("planId") REFERENCES "gym_tracker"."workout_plan"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "workout_plan_userId_index" ON "gym_tracker"."workout_plan" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "workout_plan_deletedAt_index" ON "gym_tracker"."workout_plan" USING btree ("deletedAt");--> statement-breakpoint
CREATE INDEX "workout_type_exercise_sets_workoutTypeId_index" ON "gym_tracker"."workout_type_exercise_sets" USING btree ("workoutTypeId");--> statement-breakpoint
CREATE INDEX "workout_type_exercise_sets_exerciseId_index" ON "gym_tracker"."workout_type_exercise_sets" USING btree ("exerciseId");--> statement-breakpoint
CREATE INDEX "workout_type_exercise_sets_userId_index" ON "gym_tracker"."workout_type_exercise_sets" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "workout_type_exercise_sets_workoutTypeExerciseId_index" ON "gym_tracker"."workout_type_exercise_sets" USING btree ("workoutTypeExerciseId");--> statement-breakpoint
CREATE INDEX "workout_type_exercise_userId_index" ON "gym_tracker"."workout_type_exercise" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "workout_type_exercise_deletedAt_index" ON "gym_tracker"."workout_type_exercise" USING btree ("deletedAt");--> statement-breakpoint
CREATE INDEX "workout_type_userId_index" ON "gym_tracker"."workout_type" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "workout_type_deletedAt_index" ON "gym_tracker"."workout_type" USING btree ("deletedAt");--> statement-breakpoint
ALTER TABLE "gym_tracker"."workouts" ADD CONSTRAINT "workouts_typeId_workout_type_id_fk" FOREIGN KEY ("typeId") REFERENCES "gym_tracker"."workout_type"("id") ON DELETE restrict ON UPDATE no action;