CREATE TYPE "gym_tracker"."language" AS ENUM('en', 'ru');--> statement-breakpoint
CREATE TYPE "gym_tracker"."TranslationType" AS ENUM('ExeciseName', 'ExeciseDescription');--> statement-breakpoint
CREATE TABLE "gym_tracker"."translations" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "gym_tracker"."translations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"key" varchar NOT NULL,
	"value" text NOT NULL,
	"type" "gym_tracker"."TranslationType" NOT NULL,
	"language" "gym_tracker"."language" NOT NULL,
	"auto" boolean NOT NULL,
	"locked" boolean NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone,
	"deletedAt" timestamp with time zone,
	CONSTRAINT "translations_key_type_language_unique" UNIQUE("key","type","language")
);
--> statement-breakpoint
CREATE INDEX "translations_type_index" ON "gym_tracker"."translations" USING btree ("type");--> statement-breakpoint
CREATE INDEX "translations_language_type_key_index" ON "gym_tracker"."translations" USING btree ("language","type","key");--> statement-breakpoint
CREATE INDEX "translations_createdAt_index" ON "gym_tracker"."translations" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "translations_updatedAt_index" ON "gym_tracker"."translations" USING btree ("updatedAt");