ALTER TABLE "gym_tracker"."entries" ALTER COLUMN "type" SET DATA TYPE text;--> statement-breakpoint
DROP TYPE "gym_tracker"."EntryType";--> statement-breakpoint
CREATE TYPE "gym_tracker"."EntryType" AS ENUM('Workout', 'Weight', 'Post','OutdoorRun');--> statement-breakpoint
ALTER TABLE "gym_tracker"."entries" ALTER COLUMN "type" SET DATA TYPE "gym_tracker"."EntryType" USING "type"::"gym_tracker"."EntryType";

CREATE TABLE "gym_tracker"."geo_data" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "gym_tracker"."geo_data_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"outdoorRunId" integer NOT NULL,
	"latitude" real NOT NULL,
	"longitude" real NOT NULL,
	"altitude" real NOT NULL,
	"timestamp" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "gym_tracker"."outdoor_runs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "gym_tracker"."outdoor_runs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" integer NOT NULL,
	"distance" real NOT NULL,
	"pace" real NOT NULL,
	"cadence" real NOT NULL,
	"duration" integer NOT NULL,
	"calories" integer NOT NULL,
	"start" timestamp with time zone NOT NULL,
	"end" timestamp with time zone NOT NULL
);
--> statement-breakpoint
ALTER TABLE "gym_tracker"."entries" ADD COLUMN "outdoorRunId" integer;--> statement-breakpoint
ALTER TABLE "gym_tracker"."geo_data" ADD CONSTRAINT "geo_data_outdoorRunId_outdoor_runs_id_fk" FOREIGN KEY ("outdoorRunId") REFERENCES "gym_tracker"."outdoor_runs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "gym_tracker"."outdoor_runs" ADD CONSTRAINT "outdoor_runs_userId_users_id_fk" FOREIGN KEY ("userId") REFERENCES "gym_tracker"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "gym_tracker"."entries" ADD CONSTRAINT "entries_outdoorRunId_outdoor_runs_id_fk" FOREIGN KEY ("outdoorRunId") REFERENCES "gym_tracker"."outdoor_runs"("id") ON DELETE cascade ON UPDATE no action;