CREATE TABLE "gym_tracker"."food_components" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "gym_tracker"."food_components_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"dishId" uuid NOT NULL,
	"foodId" uuid NOT NULL,
	"amount" real,
	"servings" real,
	"unit" varchar NOT NULL
);
--> statement-breakpoint
ALTER TABLE "gym_tracker"."food_components" ADD CONSTRAINT "food_components_dishId_food_id_fk" FOREIGN KEY ("dishId") REFERENCES "gym_tracker"."food"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "gym_tracker"."food_components" ADD CONSTRAINT "food_components_foodId_food_id_fk" FOREIGN KEY ("foodId") REFERENCES "gym_tracker"."food"("id") ON DELETE restrict ON UPDATE no action;