ALTER TABLE "gym_tracker"."entries" ALTER COLUMN "type" SET DATA TYPE text;--> statement-breakpoint
DROP TYPE "gym_tracker"."EntryType";--> statement-breakpoint
CREATE TYPE "gym_tracker"."EntryType" AS ENUM('Workout', 'Weight', 'Post','OutdoorRun','OutdoorWalk','Meal');--> statement-breakpoint
ALTER TABLE "gym_tracker"."entries" ALTER COLUMN "type" SET DATA TYPE "gym_tracker"."EntryType" USING "type"::"gym_tracker"."EntryType";
CREATE TYPE "gym_tracker"."MealType" AS ENUM('Breakfast', 'Lunch', 'Dinner', 'Snack', 'Other');--> statement-breakpoint

CREATE TABLE "gym_tracker"."meal_food" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "gym_tracker"."meal_food_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"mealId" integer NOT NULL,
	"foodId" uuid NOT NULL,
	"amount" real NOT NULL,
	"unit" "gym_tracker"."FoodAmountUnit" NOT NULL
);
--> statement-breakpoint
CREATE TABLE "gym_tracker"."meals" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "gym_tracker"."meals_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" integer NOT NULL,
	"type" "gym_tracker"."MealType" NOT NULL
);
--> statement-breakpoint
ALTER TABLE "gym_tracker"."entries" ADD COLUMN "mealId" integer;--> statement-breakpoint
ALTER TABLE "gym_tracker"."meal_food" ADD CONSTRAINT "meal_food_mealId_meals_id_fk" FOREIGN KEY ("mealId") REFERENCES "gym_tracker"."meals"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "gym_tracker"."meal_food" ADD CONSTRAINT "meal_food_foodId_food_id_fk" FOREIGN KEY ("foodId") REFERENCES "gym_tracker"."food"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "gym_tracker"."meals" ADD CONSTRAINT "meals_userId_users_id_fk" FOREIGN KEY ("userId") REFERENCES "gym_tracker"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "gym_tracker"."entries" ADD CONSTRAINT "entries_mealId_meals_id_fk" FOREIGN KEY ("mealId") REFERENCES "gym_tracker"."meals"("id") ON DELETE cascade ON UPDATE no action;