ALTER TABLE "gym_tracker"."entries" ALTER COLUMN "type" SET DATA TYPE text;--> statement-breakpoint
DROP TYPE "gym_tracker"."EntryType";--> statement-breakpoint
CREATE TYPE "gym_tracker"."EntryType" AS ENUM('Workout', 'Weight', 'Post','OutdoorRun','OutdoorWalk','Meal','CalorieGoal');--> statement-breakpoint
ALTER TABLE "gym_tracker"."entries" ALTER COLUMN "type" SET DATA TYPE "gym_tracker"."EntryType" USING "type"::"gym_tracker"."EntryType";--> statement-breakpoint
CREATE TABLE "gym_tracker"."calorie_goals" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "gym_tracker"."calorie_goals_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" integer NOT NULL,
	"calories" real NOT NULL,
	"carbs" real NOT NULL,
	"protein" real NOT NULL,
	"fat" real NOT NULL,
	"start" timestamp with time zone NOT NULL,
	"end" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "gym_tracker"."entries" ADD COLUMN "calorieGoalId" integer;--> statement-breakpoint
ALTER TABLE "gym_tracker"."calorie_goals" ADD CONSTRAINT "calorie_goals_userId_users_id_fk" FOREIGN KEY ("userId") REFERENCES "gym_tracker"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "gym_tracker"."entries" ADD CONSTRAINT "entries_calorieGoalId_calorie_goals_id_fk" FOREIGN KEY ("calorieGoalId") REFERENCES "gym_tracker"."calorie_goals"("id") ON DELETE cascade ON UPDATE no action;