CREATE TABLE "gym_tracker"."outdoor_run_geo_data" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "gym_tracker"."outdoor_run_geo_data_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"outdoorRunId" integer NOT NULL,
	"latitude" double precision NOT NULL,
	"longitude" double precision NOT NULL,
	"altitude" double precision NOT NULL,
	"course" double precision,
	"speed" double precision,
	"speedAccuracy" double precision,
	"horizontalAccuracy" double precision,
	"verticalAccuracy" double precision,
	"distance" double precision,
	"timestamp" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "gym_tracker"."outdoor_run_heart_rate_data" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "gym_tracker"."outdoor_run_heart_rate_data_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"outdoorRunId" integer NOT NULL,
	"heartRate" integer NOT NULL,
	"timestamp" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "gym_tracker"."outdoor_walk_geo_data" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "gym_tracker"."outdoor_walk_geo_data_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"outdoorWalkId" integer NOT NULL,
	"latitude" double precision NOT NULL,
	"longitude" double precision NOT NULL,
	"altitude" double precision NOT NULL,
	"course" double precision,
	"speed" double precision,
	"speedAccuracy" double precision,
	"horizontalAccuracy" double precision,
	"verticalAccuracy" double precision,
	"distance" double precision,
	"timestamp" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "gym_tracker"."outdoor_walk_heart_rate_data" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "gym_tracker"."outdoor_walk_heart_rate_data_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"outdoorWalkId" integer NOT NULL,
	"heartRate" integer NOT NULL,
	"timestamp" bigint NOT NULL
);
--> statement-breakpoint
ALTER TABLE "gym_tracker"."outdoor_run_geo_data" ADD CONSTRAINT "outdoor_run_geo_data_outdoorRunId_outdoor_runs_id_fk" FOREIGN KEY ("outdoorRunId") REFERENCES "gym_tracker"."outdoor_runs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "gym_tracker"."outdoor_run_heart_rate_data" ADD CONSTRAINT "outdoor_run_heart_rate_data_outdoorRunId_outdoor_runs_id_fk" FOREIGN KEY ("outdoorRunId") REFERENCES "gym_tracker"."outdoor_runs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "gym_tracker"."outdoor_walk_geo_data" ADD CONSTRAINT "outdoor_walk_geo_data_outdoorWalkId_outdoor_walks_id_fk" FOREIGN KEY ("outdoorWalkId") REFERENCES "gym_tracker"."outdoor_walks"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "gym_tracker"."outdoor_walk_heart_rate_data" ADD CONSTRAINT "outdoor_walk_heart_rate_data_outdoorWalkId_outdoor_walks_id_fk" FOREIGN KEY ("outdoorWalkId") REFERENCES "gym_tracker"."outdoor_walks"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "outdoor_run_geo_data_outdoorRunId_timestamp_index" ON "gym_tracker"."outdoor_run_geo_data" USING btree ("outdoorRunId","timestamp");--> statement-breakpoint
CREATE INDEX "outdoor_run_heart_rate_data_outdoorRunId_timestamp_index" ON "gym_tracker"."outdoor_run_heart_rate_data" USING btree ("outdoorRunId","timestamp");--> statement-breakpoint
CREATE INDEX "outdoor_walk_geo_data_outdoorWalkId_timestamp_index" ON "gym_tracker"."outdoor_walk_geo_data" USING btree ("outdoorWalkId","timestamp");--> statement-breakpoint
CREATE INDEX "outdoor_walk_heart_rate_data_outdoorWalkId_timestamp_index" ON "gym_tracker"."outdoor_walk_heart_rate_data" USING btree ("outdoorWalkId","timestamp");