CREATE TABLE "gym_tracker"."fatsecret_food_requests" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "gym_tracker"."fatsecret_food_requests_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"searchExpression" varchar NOT NULL,
	"pageNumber" integer NOT NULL,
	"pageSize" integer NOT NULL,
	"totalResults" integer NOT NULL,
	"currentPage" integer NOT NULL,
	"resultsPerPage" integer NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "gym_tracker"."fatsecret_food_responses" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "gym_tracker"."fatsecret_food_responses_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"requestId" integer NOT NULL,
	"externalId" bigint NOT NULL,
	"title" varchar NOT NULL,
	"status" varchar NOT NULL,
	"source" varchar NOT NULL,
	"shortDescription" text,
	"energyPerPortion" real NOT NULL,
	"carbohydratePerPortion" real NOT NULL,
	"proteinPerPortion" real NOT NULL,
	"fatPerPortion" real NOT NULL,
	"gramsPerPortion" real NOT NULL,
	"userName" varchar NOT NULL,
	"pathName" varchar NOT NULL,
	"defaultPortionId" integer NOT NULL,
	"defaultPortionAmount" integer NOT NULL,
	"defaultPortionDescription" varchar NOT NULL,
	"defaultEnergyPerPortion" real NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
ALTER TABLE "gym_tracker"."fatsecret_food_responses" ADD CONSTRAINT "fatsecret_food_responses_requestId_fatsecret_food_requests_id_fk" FOREIGN KEY ("requestId") REFERENCES "gym_tracker"."fatsecret_food_requests"("id") ON DELETE cascade ON UPDATE no action;