CREATE TABLE "gym_tracker"."fatsecret_barcode_scan_responses" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "gym_tracker"."fatsecret_barcode_scan_responses_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"barcode" varchar NOT NULL,
	"foodId" bigint,
	"barcodeId" bigint,
	"deviceCanPrompt" boolean,
	"createdAt" timestamp with time zone NOT NULL
);
