/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FeedIndexRouteImport } from './routes/feed/index'
import { Route as ExercisesIndexRouteImport } from './routes/exercises/index'
import { Route as EntriesIndexRouteImport } from './routes/entries/index'
import { Route as CrmIndexRouteImport } from './routes/crm/index'
import { Route as ArgusIndexRouteImport } from './routes/argus/index'
import { Route as WorkoutsCreateRouteImport } from './routes/workouts/create'
import { Route as WeightCreateRouteImport } from './routes/weight/create'
import { Route as ExercisesCreateRouteImport } from './routes/exercises/create'
import { Route as ExercisesExerciseIdRouteImport } from './routes/exercises/$exerciseId'
import { Route as EntriesAddRouteImport } from './routes/entries/add'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as ArticlesTermsOfServiceRouteImport } from './routes/articles/terms-of-service'
import { Route as ArticlesPrivacyPolicyRouteImport } from './routes/articles/privacy-policy'
import { Route as WorkoutsTypesIndexRouteImport } from './routes/workouts/types/index'
import { Route as WorkoutsPlansIndexRouteImport } from './routes/workouts/plans/index'
import { Route as CrmUsersIndexRouteImport } from './routes/crm/users/index'
import { Route as CrmTranslationsIndexRouteImport } from './routes/crm/translations/index'
import { Route as CrmManagersIndexRouteImport } from './routes/crm/managers/index'
import { Route as WorkoutsUpdateIdRouteImport } from './routes/workouts/update/$id'
import { Route as WorkoutsTypesCreateRouteImport } from './routes/workouts/types/create'
import { Route as WorkoutsPlansCreateRouteImport } from './routes/workouts/plans/create'
import { Route as WeightUpdateIdRouteImport } from './routes/weight/update/$id'
import { Route as ExercisesUpdateExerciseIdRouteImport } from './routes/exercises/update/$exerciseId'
import { Route as WorkoutsTypesUpdateIdRouteImport } from './routes/workouts/types/update/$id'
import { Route as WorkoutsPlansUpdateIdRouteImport } from './routes/workouts/plans/update/$id'
import { ServerRoute as SwaggerServerRouteImport } from './routes/swagger'
import { ServerRoute as StoplightServerRouteImport } from './routes/stoplight'
import { ServerRoute as SchemaServerRouteImport } from './routes/schema'
import { ServerRoute as ApiServerRouteImport } from './routes/api'

const rootServerRouteImport = createServerRootRoute()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedIndexRoute = FeedIndexRouteImport.update({
  id: '/feed/',
  path: '/feed/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesIndexRoute = ExercisesIndexRouteImport.update({
  id: '/exercises/',
  path: '/exercises/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntriesIndexRoute = EntriesIndexRouteImport.update({
  id: '/entries/',
  path: '/entries/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmIndexRoute = CrmIndexRouteImport.update({
  id: '/crm/',
  path: '/crm/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArgusIndexRoute = ArgusIndexRouteImport.update({
  id: '/argus/',
  path: '/argus/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsCreateRoute = WorkoutsCreateRouteImport.update({
  id: '/workouts/create',
  path: '/workouts/create',
  getParentRoute: () => rootRouteImport,
} as any)
const WeightCreateRoute = WeightCreateRouteImport.update({
  id: '/weight/create',
  path: '/weight/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesCreateRoute = ExercisesCreateRouteImport.update({
  id: '/exercises/create',
  path: '/exercises/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesExerciseIdRoute = ExercisesExerciseIdRouteImport.update({
  id: '/exercises/$exerciseId',
  path: '/exercises/$exerciseId',
  getParentRoute: () => rootRouteImport,
} as any)
const EntriesAddRoute = EntriesAddRouteImport.update({
  id: '/entries/add',
  path: '/entries/add',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesTermsOfServiceRoute = ArticlesTermsOfServiceRouteImport.update({
  id: '/articles/terms-of-service',
  path: '/articles/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesPrivacyPolicyRoute = ArticlesPrivacyPolicyRouteImport.update({
  id: '/articles/privacy-policy',
  path: '/articles/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsTypesIndexRoute = WorkoutsTypesIndexRouteImport.update({
  id: '/workouts/types/',
  path: '/workouts/types/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsPlansIndexRoute = WorkoutsPlansIndexRouteImport.update({
  id: '/workouts/plans/',
  path: '/workouts/plans/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmUsersIndexRoute = CrmUsersIndexRouteImport.update({
  id: '/crm/users/',
  path: '/crm/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmTranslationsIndexRoute = CrmTranslationsIndexRouteImport.update({
  id: '/crm/translations/',
  path: '/crm/translations/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmManagersIndexRoute = CrmManagersIndexRouteImport.update({
  id: '/crm/managers/',
  path: '/crm/managers/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsUpdateIdRoute = WorkoutsUpdateIdRouteImport.update({
  id: '/workouts/update/$id',
  path: '/workouts/update/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsTypesCreateRoute = WorkoutsTypesCreateRouteImport.update({
  id: '/workouts/types/create',
  path: '/workouts/types/create',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsPlansCreateRoute = WorkoutsPlansCreateRouteImport.update({
  id: '/workouts/plans/create',
  path: '/workouts/plans/create',
  getParentRoute: () => rootRouteImport,
} as any)
const WeightUpdateIdRoute = WeightUpdateIdRouteImport.update({
  id: '/weight/update/$id',
  path: '/weight/update/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesUpdateExerciseIdRoute =
  ExercisesUpdateExerciseIdRouteImport.update({
    id: '/exercises/update/$exerciseId',
    path: '/exercises/update/$exerciseId',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkoutsTypesUpdateIdRoute = WorkoutsTypesUpdateIdRouteImport.update({
  id: '/workouts/types/update/$id',
  path: '/workouts/types/update/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsPlansUpdateIdRoute = WorkoutsPlansUpdateIdRouteImport.update({
  id: '/workouts/plans/update/$id',
  path: '/workouts/plans/update/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SwaggerServerRoute = SwaggerServerRouteImport.update({
  id: '/swagger',
  path: '/swagger',
  getParentRoute: () => rootServerRouteImport,
} as any)
const StoplightServerRoute = StoplightServerRouteImport.update({
  id: '/stoplight',
  path: '/stoplight',
  getParentRoute: () => rootServerRouteImport,
} as any)
const SchemaServerRoute = SchemaServerRouteImport.update({
  id: '/schema',
  path: '/schema',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiServerRoute = ApiServerRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/articles/privacy-policy': typeof ArticlesPrivacyPolicyRoute
  '/articles/terms-of-service': typeof ArticlesTermsOfServiceRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/entries/add': typeof EntriesAddRoute
  '/exercises/$exerciseId': typeof ExercisesExerciseIdRoute
  '/exercises/create': typeof ExercisesCreateRoute
  '/weight/create': typeof WeightCreateRoute
  '/workouts/create': typeof WorkoutsCreateRoute
  '/argus': typeof ArgusIndexRoute
  '/crm': typeof CrmIndexRoute
  '/entries': typeof EntriesIndexRoute
  '/exercises': typeof ExercisesIndexRoute
  '/feed': typeof FeedIndexRoute
  '/exercises/update/$exerciseId': typeof ExercisesUpdateExerciseIdRoute
  '/weight/update/$id': typeof WeightUpdateIdRoute
  '/workouts/plans/create': typeof WorkoutsPlansCreateRoute
  '/workouts/types/create': typeof WorkoutsTypesCreateRoute
  '/workouts/update/$id': typeof WorkoutsUpdateIdRoute
  '/crm/managers': typeof CrmManagersIndexRoute
  '/crm/translations': typeof CrmTranslationsIndexRoute
  '/crm/users': typeof CrmUsersIndexRoute
  '/workouts/plans': typeof WorkoutsPlansIndexRoute
  '/workouts/types': typeof WorkoutsTypesIndexRoute
  '/workouts/plans/update/$id': typeof WorkoutsPlansUpdateIdRoute
  '/workouts/types/update/$id': typeof WorkoutsTypesUpdateIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/articles/privacy-policy': typeof ArticlesPrivacyPolicyRoute
  '/articles/terms-of-service': typeof ArticlesTermsOfServiceRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/entries/add': typeof EntriesAddRoute
  '/exercises/$exerciseId': typeof ExercisesExerciseIdRoute
  '/exercises/create': typeof ExercisesCreateRoute
  '/weight/create': typeof WeightCreateRoute
  '/workouts/create': typeof WorkoutsCreateRoute
  '/argus': typeof ArgusIndexRoute
  '/crm': typeof CrmIndexRoute
  '/entries': typeof EntriesIndexRoute
  '/exercises': typeof ExercisesIndexRoute
  '/feed': typeof FeedIndexRoute
  '/exercises/update/$exerciseId': typeof ExercisesUpdateExerciseIdRoute
  '/weight/update/$id': typeof WeightUpdateIdRoute
  '/workouts/plans/create': typeof WorkoutsPlansCreateRoute
  '/workouts/types/create': typeof WorkoutsTypesCreateRoute
  '/workouts/update/$id': typeof WorkoutsUpdateIdRoute
  '/crm/managers': typeof CrmManagersIndexRoute
  '/crm/translations': typeof CrmTranslationsIndexRoute
  '/crm/users': typeof CrmUsersIndexRoute
  '/workouts/plans': typeof WorkoutsPlansIndexRoute
  '/workouts/types': typeof WorkoutsTypesIndexRoute
  '/workouts/plans/update/$id': typeof WorkoutsPlansUpdateIdRoute
  '/workouts/types/update/$id': typeof WorkoutsTypesUpdateIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/articles/privacy-policy': typeof ArticlesPrivacyPolicyRoute
  '/articles/terms-of-service': typeof ArticlesTermsOfServiceRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/entries/add': typeof EntriesAddRoute
  '/exercises/$exerciseId': typeof ExercisesExerciseIdRoute
  '/exercises/create': typeof ExercisesCreateRoute
  '/weight/create': typeof WeightCreateRoute
  '/workouts/create': typeof WorkoutsCreateRoute
  '/argus/': typeof ArgusIndexRoute
  '/crm/': typeof CrmIndexRoute
  '/entries/': typeof EntriesIndexRoute
  '/exercises/': typeof ExercisesIndexRoute
  '/feed/': typeof FeedIndexRoute
  '/exercises/update/$exerciseId': typeof ExercisesUpdateExerciseIdRoute
  '/weight/update/$id': typeof WeightUpdateIdRoute
  '/workouts/plans/create': typeof WorkoutsPlansCreateRoute
  '/workouts/types/create': typeof WorkoutsTypesCreateRoute
  '/workouts/update/$id': typeof WorkoutsUpdateIdRoute
  '/crm/managers/': typeof CrmManagersIndexRoute
  '/crm/translations/': typeof CrmTranslationsIndexRoute
  '/crm/users/': typeof CrmUsersIndexRoute
  '/workouts/plans/': typeof WorkoutsPlansIndexRoute
  '/workouts/types/': typeof WorkoutsTypesIndexRoute
  '/workouts/plans/update/$id': typeof WorkoutsPlansUpdateIdRoute
  '/workouts/types/update/$id': typeof WorkoutsTypesUpdateIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/articles/privacy-policy'
    | '/articles/terms-of-service'
    | '/auth/login'
    | '/auth/register'
    | '/entries/add'
    | '/exercises/$exerciseId'
    | '/exercises/create'
    | '/weight/create'
    | '/workouts/create'
    | '/argus'
    | '/crm'
    | '/entries'
    | '/exercises'
    | '/feed'
    | '/exercises/update/$exerciseId'
    | '/weight/update/$id'
    | '/workouts/plans/create'
    | '/workouts/types/create'
    | '/workouts/update/$id'
    | '/crm/managers'
    | '/crm/translations'
    | '/crm/users'
    | '/workouts/plans'
    | '/workouts/types'
    | '/workouts/plans/update/$id'
    | '/workouts/types/update/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/articles/privacy-policy'
    | '/articles/terms-of-service'
    | '/auth/login'
    | '/auth/register'
    | '/entries/add'
    | '/exercises/$exerciseId'
    | '/exercises/create'
    | '/weight/create'
    | '/workouts/create'
    | '/argus'
    | '/crm'
    | '/entries'
    | '/exercises'
    | '/feed'
    | '/exercises/update/$exerciseId'
    | '/weight/update/$id'
    | '/workouts/plans/create'
    | '/workouts/types/create'
    | '/workouts/update/$id'
    | '/crm/managers'
    | '/crm/translations'
    | '/crm/users'
    | '/workouts/plans'
    | '/workouts/types'
    | '/workouts/plans/update/$id'
    | '/workouts/types/update/$id'
  id:
    | '__root__'
    | '/'
    | '/articles/privacy-policy'
    | '/articles/terms-of-service'
    | '/auth/login'
    | '/auth/register'
    | '/entries/add'
    | '/exercises/$exerciseId'
    | '/exercises/create'
    | '/weight/create'
    | '/workouts/create'
    | '/argus/'
    | '/crm/'
    | '/entries/'
    | '/exercises/'
    | '/feed/'
    | '/exercises/update/$exerciseId'
    | '/weight/update/$id'
    | '/workouts/plans/create'
    | '/workouts/types/create'
    | '/workouts/update/$id'
    | '/crm/managers/'
    | '/crm/translations/'
    | '/crm/users/'
    | '/workouts/plans/'
    | '/workouts/types/'
    | '/workouts/plans/update/$id'
    | '/workouts/types/update/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArticlesPrivacyPolicyRoute: typeof ArticlesPrivacyPolicyRoute
  ArticlesTermsOfServiceRoute: typeof ArticlesTermsOfServiceRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  EntriesAddRoute: typeof EntriesAddRoute
  ExercisesExerciseIdRoute: typeof ExercisesExerciseIdRoute
  ExercisesCreateRoute: typeof ExercisesCreateRoute
  WeightCreateRoute: typeof WeightCreateRoute
  WorkoutsCreateRoute: typeof WorkoutsCreateRoute
  ArgusIndexRoute: typeof ArgusIndexRoute
  CrmIndexRoute: typeof CrmIndexRoute
  EntriesIndexRoute: typeof EntriesIndexRoute
  ExercisesIndexRoute: typeof ExercisesIndexRoute
  FeedIndexRoute: typeof FeedIndexRoute
  ExercisesUpdateExerciseIdRoute: typeof ExercisesUpdateExerciseIdRoute
  WeightUpdateIdRoute: typeof WeightUpdateIdRoute
  WorkoutsPlansCreateRoute: typeof WorkoutsPlansCreateRoute
  WorkoutsTypesCreateRoute: typeof WorkoutsTypesCreateRoute
  WorkoutsUpdateIdRoute: typeof WorkoutsUpdateIdRoute
  CrmManagersIndexRoute: typeof CrmManagersIndexRoute
  CrmTranslationsIndexRoute: typeof CrmTranslationsIndexRoute
  CrmUsersIndexRoute: typeof CrmUsersIndexRoute
  WorkoutsPlansIndexRoute: typeof WorkoutsPlansIndexRoute
  WorkoutsTypesIndexRoute: typeof WorkoutsTypesIndexRoute
  WorkoutsPlansUpdateIdRoute: typeof WorkoutsPlansUpdateIdRoute
  WorkoutsTypesUpdateIdRoute: typeof WorkoutsTypesUpdateIdRoute
}
export interface FileServerRoutesByFullPath {
  '/api': typeof ApiServerRoute
  '/schema': typeof SchemaServerRoute
  '/stoplight': typeof StoplightServerRoute
  '/swagger': typeof SwaggerServerRoute
}
export interface FileServerRoutesByTo {
  '/api': typeof ApiServerRoute
  '/schema': typeof SchemaServerRoute
  '/stoplight': typeof StoplightServerRoute
  '/swagger': typeof SwaggerServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api': typeof ApiServerRoute
  '/schema': typeof SchemaServerRoute
  '/stoplight': typeof StoplightServerRoute
  '/swagger': typeof SwaggerServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api' | '/schema' | '/stoplight' | '/swagger'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api' | '/schema' | '/stoplight' | '/swagger'
  id: '__root__' | '/api' | '/schema' | '/stoplight' | '/swagger'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiServerRoute: typeof ApiServerRoute
  SchemaServerRoute: typeof SchemaServerRoute
  StoplightServerRoute: typeof StoplightServerRoute
  SwaggerServerRoute: typeof SwaggerServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/': {
      id: '/feed/'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/': {
      id: '/exercises/'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof ExercisesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entries/': {
      id: '/entries/'
      path: '/entries'
      fullPath: '/entries'
      preLoaderRoute: typeof EntriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/': {
      id: '/crm/'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/argus/': {
      id: '/argus/'
      path: '/argus'
      fullPath: '/argus'
      preLoaderRoute: typeof ArgusIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/create': {
      id: '/workouts/create'
      path: '/workouts/create'
      fullPath: '/workouts/create'
      preLoaderRoute: typeof WorkoutsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weight/create': {
      id: '/weight/create'
      path: '/weight/create'
      fullPath: '/weight/create'
      preLoaderRoute: typeof WeightCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/create': {
      id: '/exercises/create'
      path: '/exercises/create'
      fullPath: '/exercises/create'
      preLoaderRoute: typeof ExercisesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/$exerciseId': {
      id: '/exercises/$exerciseId'
      path: '/exercises/$exerciseId'
      fullPath: '/exercises/$exerciseId'
      preLoaderRoute: typeof ExercisesExerciseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entries/add': {
      id: '/entries/add'
      path: '/entries/add'
      fullPath: '/entries/add'
      preLoaderRoute: typeof EntriesAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/terms-of-service': {
      id: '/articles/terms-of-service'
      path: '/articles/terms-of-service'
      fullPath: '/articles/terms-of-service'
      preLoaderRoute: typeof ArticlesTermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/privacy-policy': {
      id: '/articles/privacy-policy'
      path: '/articles/privacy-policy'
      fullPath: '/articles/privacy-policy'
      preLoaderRoute: typeof ArticlesPrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/types/': {
      id: '/workouts/types/'
      path: '/workouts/types'
      fullPath: '/workouts/types'
      preLoaderRoute: typeof WorkoutsTypesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/plans/': {
      id: '/workouts/plans/'
      path: '/workouts/plans'
      fullPath: '/workouts/plans'
      preLoaderRoute: typeof WorkoutsPlansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/users/': {
      id: '/crm/users/'
      path: '/crm/users'
      fullPath: '/crm/users'
      preLoaderRoute: typeof CrmUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/translations/': {
      id: '/crm/translations/'
      path: '/crm/translations'
      fullPath: '/crm/translations'
      preLoaderRoute: typeof CrmTranslationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/managers/': {
      id: '/crm/managers/'
      path: '/crm/managers'
      fullPath: '/crm/managers'
      preLoaderRoute: typeof CrmManagersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/update/$id': {
      id: '/workouts/update/$id'
      path: '/workouts/update/$id'
      fullPath: '/workouts/update/$id'
      preLoaderRoute: typeof WorkoutsUpdateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/types/create': {
      id: '/workouts/types/create'
      path: '/workouts/types/create'
      fullPath: '/workouts/types/create'
      preLoaderRoute: typeof WorkoutsTypesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/plans/create': {
      id: '/workouts/plans/create'
      path: '/workouts/plans/create'
      fullPath: '/workouts/plans/create'
      preLoaderRoute: typeof WorkoutsPlansCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weight/update/$id': {
      id: '/weight/update/$id'
      path: '/weight/update/$id'
      fullPath: '/weight/update/$id'
      preLoaderRoute: typeof WeightUpdateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/update/$exerciseId': {
      id: '/exercises/update/$exerciseId'
      path: '/exercises/update/$exerciseId'
      fullPath: '/exercises/update/$exerciseId'
      preLoaderRoute: typeof ExercisesUpdateExerciseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/types/update/$id': {
      id: '/workouts/types/update/$id'
      path: '/workouts/types/update/$id'
      fullPath: '/workouts/types/update/$id'
      preLoaderRoute: typeof WorkoutsTypesUpdateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/plans/update/$id': {
      id: '/workouts/plans/update/$id'
      path: '/workouts/plans/update/$id'
      fullPath: '/workouts/plans/update/$id'
      preLoaderRoute: typeof WorkoutsPlansUpdateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/swagger': {
      id: '/swagger'
      path: '/swagger'
      fullPath: '/swagger'
      preLoaderRoute: typeof SwaggerServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/stoplight': {
      id: '/stoplight'
      path: '/stoplight'
      fullPath: '/stoplight'
      preLoaderRoute: typeof StoplightServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/schema': {
      id: '/schema'
      path: '/schema'
      fullPath: '/schema'
      preLoaderRoute: typeof SchemaServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArticlesPrivacyPolicyRoute: ArticlesPrivacyPolicyRoute,
  ArticlesTermsOfServiceRoute: ArticlesTermsOfServiceRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  EntriesAddRoute: EntriesAddRoute,
  ExercisesExerciseIdRoute: ExercisesExerciseIdRoute,
  ExercisesCreateRoute: ExercisesCreateRoute,
  WeightCreateRoute: WeightCreateRoute,
  WorkoutsCreateRoute: WorkoutsCreateRoute,
  ArgusIndexRoute: ArgusIndexRoute,
  CrmIndexRoute: CrmIndexRoute,
  EntriesIndexRoute: EntriesIndexRoute,
  ExercisesIndexRoute: ExercisesIndexRoute,
  FeedIndexRoute: FeedIndexRoute,
  ExercisesUpdateExerciseIdRoute: ExercisesUpdateExerciseIdRoute,
  WeightUpdateIdRoute: WeightUpdateIdRoute,
  WorkoutsPlansCreateRoute: WorkoutsPlansCreateRoute,
  WorkoutsTypesCreateRoute: WorkoutsTypesCreateRoute,
  WorkoutsUpdateIdRoute: WorkoutsUpdateIdRoute,
  CrmManagersIndexRoute: CrmManagersIndexRoute,
  CrmTranslationsIndexRoute: CrmTranslationsIndexRoute,
  CrmUsersIndexRoute: CrmUsersIndexRoute,
  WorkoutsPlansIndexRoute: WorkoutsPlansIndexRoute,
  WorkoutsTypesIndexRoute: WorkoutsTypesIndexRoute,
  WorkoutsPlansUpdateIdRoute: WorkoutsPlansUpdateIdRoute,
  WorkoutsTypesUpdateIdRoute: WorkoutsTypesUpdateIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiServerRoute: ApiServerRoute,
  SchemaServerRoute: SchemaServerRoute,
  StoplightServerRoute: StoplightServerRoute,
  SwaggerServerRoute: SwaggerServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
