export enum EntryType {
  Steps = 'steps',
  Weather = 'weather',
  Calories ='calories',
  Food ='food',
  Activity ='activity',
  Weight ='weight',
  ConsumedCalories='consumedcalories',
  Drink='drink',
  Heartrate='heartrate',
  Status='status',
  Bodymetrics='bodymetrics',
  WorkoutLog='workout_log',
  Sleepreport='sleepreport',
  FitnessTest='fitnesstest',
}
