name: Test
run-name: ${{ github.actor }} running tests
on: 
  pull_request:
    branches: [main]
  push:
    branches: [ main ]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - name: Check Out Repo
        uses: actions/checkout@v4
      - name: Setup docker-compose
        uses: KengoTODA/actions-setup-docker-compose@main
        with:
          version: '2.31.0'
      - run: ls -al .
      - name: Starting containers
        run: docker-compose up -d --no-color --wait db
      - run: npm install
      - run: npm run db:migrate
      - run: npm run lint
      - run: npm run test:typecheck
      - run: npm run test:gha
